import { createHash, randomUUID } from 'node:crypto';
import type { Database } from 'bun:sqlite';
import { z } from 'zod';
import { all, one, required } from './queries';
import { WorkspaceConflictError, type Evidence, type Work } from './types';
import type { ChatCitation } from './conversations';
import { renderWord } from './word-output';
import type { PreparedRedline } from './redlines';
import { wordOutputFilename, wordFilename, FilenamePattern, RevisionAuthor, type PreferenceSnapshot } from './working-preferences';
import { requireActiveRecord } from './record-lifecycle';
import { CleanProposalRequest, generateCleanProposal } from './clean-proposals';

export const WORD_TEMPLATE = 'counsel-word-v1';
export const WORD_MEDIA_TYPE =
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
export interface ExportSnapshot {
  wordPreferences?: PreferenceSnapshot['word'];
  workId: string;
  title: string;
  answer: string;
  disposition: Work['disposition'];
  recordedAt: string;
  decisionBy: string | null;
  contentHash: string;
  origin: Work['origin'];
  evidence: Array<Omit<Evidence, 'provenance'> & { key: string | null; coverage: string | null }>;
}
export interface WordExport {
  id: string;
  workId: string;
  name: string;
  createdAt: string;
  template: string;
  inputHash: string;
  contentHash: string;
  byteCount: number;
  warnings: string[];
}
export function hashBytes(bytes: Uint8Array | string): string {
  return createHash('sha256').update(bytes).digest('hex');
}
export function exportSnapshot(
  work: Work,
  citations: ChatCitation[],
  coverage: Map<string, string>,
): ExportSnapshot {
  if (!work.answer.trim()) throw new WorkspaceConflictError('This answer has no text to export.');
  if (hashBytes(work.answer) !== work.contentHash)
    throw new WorkspaceConflictError('The saved answer failed its integrity check.');
  const evidence = work.evidence.map(({ provenance: _privateLocation, ...e }) => {
    const citation = citations.find(
      (c) =>
        JSON.stringify(c.target) === JSON.stringify(e.target) &&
        c.quote === e.quote &&
        c.start === e.start,
    );
    return {
      ...e,
      key: citation?.key ?? null,
      coverage: e.target.kind === 'source' ? (coverage.get(e.target.revisionId) ?? null) : null,
    };
  });
  const { id: workId, answer, disposition, recordedAt, decisionBy, contentHash, origin } = work;
  return {
    workId,
    title: work.output?.title ?? work.title,
    answer,
    disposition,
    recordedAt,
    decisionBy,
    contentHash,
    origin,
    evidence,
  };
}
const SELECT = `SELECT id, work_id AS workId, name, created_at AS createdAt, template,
  input_hash AS inputHash, content_hash AS contentHash, byte_count AS byteCount, warnings_json AS warningsJson FROM work_exports`;
type Row = Omit<WordExport, 'warnings'> & { warningsJson: string };
const unpack = ({ warningsJson, ...row }: Row): WordExport => ({
  ...row,
  warnings: JSON.parse(warningsJson),
});

/** Generated bytes and their source snapshot commit together in SQLite. No filesystem dual write. */
export class WorkspaceExports {
  private readonly pending = new Map<string, Promise<WordExport>>();
  constructor(
    private readonly db: Database,
    private readonly snapshot: (id: string) => ExportSnapshot,
    private readonly now: () => string,
    private readonly original?: (revisionId: string) => { name: string; bytes: Uint8Array },
  ) {}

  list(workId: string): WordExport[] {
    requireActiveRecord(this.db, 'work', workId);
    required(
      one(this.db, 'SELECT id FROM work_records WHERE id = ?', z.string().uuid().parse(workId)),
      `work: ${workId}`,
    );
    return all<Row>(
      this.db,
      `${SELECT} WHERE work_id = ? ORDER BY created_at DESC, id`,
      workId,
    ).map(unpack);
  }

  /** Trusted chat finalization path. Exact original identity and edits accompany the bytes. */
  retainRedline(workId: string, prepared: PreparedRedline): WordExport {
    this.list(workId); // Validate its parent record before saving an artifact.
    const snapshot = { sourceRevisionId: prepared.input.sourceRevisionId, sourceTitle: prepared.sourceTitle,
      sourceVersion: prepared.sourceVersion, originalHash: prepared.sourceHash, edits: prepared.input.edits,
      ...(prepared.input.insertions?.length ? { insertions: prepared.input.insertions } : {}), report: prepared.report,
      wordPreferences: prepared.wordPreferences };
    const template = prepared.input.insertions?.length ? 'counsel-redline-v2' : 'counsel-redline-v1';
    const inputHash = hashBytes(JSON.stringify({ template, snapshot }));
    const existing = one<Row>(this.db, `${SELECT} WHERE work_id = ? AND input_hash = ?`, workId, inputHash);
    if (existing) { this.download(existing.id); return unpack(existing); }
    let stem = '';
    for (const char of prepared.name.replace(/\.docx$/i, '').normalize('NFC').replace(/[<>:"/\\|?*\x00-\x1f\x7f]/g, '-')) {
      if (Buffer.byteLength(stem + char) > 160) break;
      stem += char;
    }
    const record: WordExport = { id: randomUUID(), workId, name: prepared.wordPreferences
      ? wordOutputFilename(prepared.wordPreferences, { document: prepared.name.replace(/\.docx$/i, ''), variant: 'redline', date: this.now().slice(0, 10) })
      : `${stem.replace(/^[. ]+|[. ]+$/g, '') || 'Document'} - redline.docx`,
      createdAt: this.now(), template, inputHash, contentHash: hashBytes(prepared.bytes),
      byteCount: prepared.bytes.length, warnings: [`AI-drafted changes attributed in Word to ${prepared.wordPreferences?.author ?? 'Counsel'}. Review them before use. Original preserved; unrelated existing revisions and comments keep their authors and are not accepted or rejected.`] };
    this.db.run('INSERT INTO work_exports VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [record.id, workId, record.name,
      record.createdAt, record.template, inputHash, record.contentHash, record.byteCount, JSON.stringify(record.warnings), JSON.stringify(snapshot), prepared.bytes]);
    return record;
  }

  private cleanInput(id: string) {
    const redline = this.download(id);
    if (!['counsel-redline-v1', 'counsel-redline-v2'].includes(redline.record.template))
      throw new WorkspaceConflictError('Create a clean proposal from a saved Counsel redline, not an answer export or another clean copy.');
    const raw = required(one<{ snapshotJson: string }>(this.db, 'SELECT snapshot_json AS snapshotJson FROM work_exports WHERE id = ?', id), 'redline snapshot');
    const saved = JSON.parse(raw.snapshotJson);
    if (hashBytes(JSON.stringify({ template: redline.record.template, snapshot: saved })) !== redline.record.inputHash)
      throw new WorkspaceConflictError('The saved redline snapshot failed its integrity check.');
    const snapshot = z.object({ sourceRevisionId: z.string().uuid(), sourceTitle: z.string(), sourceVersion: z.number().int().positive(),
      originalHash: z.string().regex(/^[a-f0-9]{64}$/), wordPreferences: z.object({ author: RevisionAuthor, filenamePattern: FilenamePattern }).passthrough().optional() }).passthrough().parse(saved);
    const template = 'counsel-clean-proposal-v1';
    const basis = { redlineId: id, redlineHash: redline.record.contentHash, redlineInputHash: redline.record.inputHash,
      sourceRevisionId: snapshot.sourceRevisionId, sourceVersion: snapshot.sourceVersion, originalHash: snapshot.originalHash,
      comments: 'retained', status: 'proposal-only' };
    return { redline, snapshot, template, basis, inputHash: hashBytes(JSON.stringify({ template, snapshot: basis })) };
  }

  cleanProposal(id: string): WordExport | null {
    const input = this.cleanInput(id);
    const existing = one<Row>(this.db, `${SELECT} WHERE work_id = ? AND input_hash = ?`, input.redline.record.workId, input.inputHash);
    return existing ? this.download(existing.id).record : null;
  }

  async createCleanProposal(id: string, raw: unknown, signal: AbortSignal): Promise<WordExport> {
    const request = CleanProposalRequest.parse(raw), input = this.cleanInput(id);
    signal.throwIfAborted();
    if (request.expectedContentHash !== input.redline.record.contentHash) throw new WorkspaceConflictError('The selected redline changed. Reopen it before creating a clean proposal.');
    const existing = this.cleanProposal(id);
    if (existing) return existing;
    const pending = this.pending.get(input.inputHash);
    if (pending) return pending;
    if (!this.original) throw new WorkspaceConflictError('Original document access is unavailable.');
    const original = this.original(input.snapshot.sourceRevisionId);
    if (hashBytes(original.bytes) !== input.snapshot.originalHash) throw new WorkspaceConflictError('The original document failed its saved redline identity check.');
    const job = (async () => {
      const output = await generateCleanProposal(original.bytes, input.redline.bytes, input.snapshot.wordPreferences?.author ?? 'Counsel', signal);
      return this.db.transaction(() => {
        signal.throwIfAborted();
        const current = this.cleanInput(id); // Recheck active parent, artifact and snapshot after the worker.
        if (current.inputHash !== input.inputHash || hashBytes(this.original!(input.snapshot.sourceRevisionId).bytes) !== input.snapshot.originalHash)
          throw new WorkspaceConflictError('Saved document state changed during preparation. No clean proposal was saved.');
        const existing = this.cleanProposal(id);
        if (existing) return existing;
        const createdAt = this.now(), word = input.snapshot.wordPreferences;
        let name = wordFilename(word?.filenamePattern ?? '{document} - {variant}', { document: original.name.replace(/\.docx$/i, ''),
          variant: 'clean proposal', date: createdAt.slice(0, 10), author: word?.author ?? 'Counsel' });
        // A pattern without {variant} must not give both artifacts the same download name.
        if ([input.redline.record.name, original.name].some(previous => previous.toLowerCase() === name.toLowerCase())) {
          let stem = '';
          for (const char of name.replace(/\.docx$/i, '')) { if (Buffer.byteLength(stem + char) > 100) break; stem += char; }
          name = wordFilename('{document} - {variant}', { document: stem, variant: 'clean proposal', date: createdAt.slice(0, 10), author: '' });
        }
        const record: WordExport = { id: randomUUID(), workId: input.redline.record.workId, name, createdAt, template: input.template,
          inputHash: input.inputHash, contentHash: hashBytes(output.bytes), byteCount: output.bytes.length,
          warnings: ['Clean proposal only: this applies the saved Counsel changes in a separate copy; it does not record acceptance, approval or execution.',
            'Original and tracked redline preserved. Review numbering, cross-references and layout before use.',
            ...(output.report.commentsRetained ? ['Comments and their authors are retained, including drafting rationale. Review comments before sharing.'] : [])] };
        this.db.run('INSERT INTO work_exports VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [record.id, record.workId, record.name, createdAt,
          record.template, record.inputHash, record.contentHash, record.byteCount, JSON.stringify(record.warnings), JSON.stringify(input.basis), output.bytes]);
        return record;
      }).immediate();
    })().finally(() => this.pending.delete(input.inputHash));
    this.pending.set(input.inputHash, job);
    return job;
  }

  async create(workId: string): Promise<WordExport> {
    const snapshot = this.snapshot(z.string().uuid().parse(workId));
    const inputHash = hashBytes(JSON.stringify({ template: WORD_TEMPLATE, snapshot }));
    const existing = one<Row>(
      this.db,
      `${SELECT} WHERE work_id = ? AND input_hash = ?`,
      workId,
      inputHash,
    );
    if (existing) {
      this.download(existing.id); // Never claim a corrupt saved artifact is reusable.
      return unpack(existing);
    }
    const key = `${workId}:${inputHash}`;
    const pending = this.pending.get(key);
    if (pending) return pending;
    if (this.pending.size >= 2)
      throw new WorkspaceConflictError(
        'Two Word exports are being prepared. Wait for one to finish and try again.',
      );
    const job = this.generate(snapshot, inputHash).finally(() => this.pending.delete(key));
    this.pending.set(key, job);
    return job;
  }

  private async generate(snapshot: ExportSnapshot, inputHash: string): Promise<WordExport> {
    const { bytes, warnings } = await renderWord(snapshot);
    if (bytes.length > 5_000_000)
      throw new WorkspaceConflictError('This Word export is too large. Export a shorter answer.');
    return this.db
      .transaction(() => {
        requireActiveRecord(this.db, 'work', snapshot.workId);
        const existing = one<Row>(
          this.db,
          `${SELECT} WHERE work_id = ? AND input_hash = ?`,
          snapshot.workId,
          inputHash,
        );
        if (existing) return unpack(existing);
        let safeTitle = '';
        for (const character of snapshot.title
          .normalize('NFC')
          .replace(/[<>:"/\\|?*\x00-\x1f\x7f]/g, '-')) {
          if (Buffer.byteLength(safeTitle + character) > 160) break;
          safeTitle += character;
        }
        safeTitle = safeTitle.replace(/^[. ]+|[. ]+$/g, '') || 'Counsel output';
        if (/^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(?:\.|$)/i.test(safeTitle))
          safeTitle = `Counsel ${safeTitle}`;
        const result: WordExport = {
          id: randomUUID(),
          workId: snapshot.workId,
          name: snapshot.wordPreferences ? wordOutputFilename(snapshot.wordPreferences,
            { document: snapshot.title, variant: 'draft', date: snapshot.recordedAt.slice(0, 10) }) : `${safeTitle}.docx`,
          createdAt: this.now(),
          template: WORD_TEMPLATE,
          inputHash,
          contentHash: hashBytes(bytes),
          byteCount: bytes.length,
          warnings,
        };
        this.db.run(`INSERT INTO work_exports VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, [
          result.id,
          result.workId,
          result.name,
          result.createdAt,
          result.template,
          inputHash,
          result.contentHash,
          bytes.length,
          JSON.stringify(warnings),
          JSON.stringify(snapshot),
          bytes,
        ]);
        return result;
      })
      .immediate();
  }

  download(id: string): { record: WordExport; bytes: Uint8Array } {
    const row = required(
      one<Row>(this.db, `${SELECT} WHERE id = ?`, z.string().uuid().parse(id)),
      `export: ${id}`,
    );
    requireActiveRecord(this.db, 'work', row.workId);
    const { bytes } = required(
      one<{ bytes: Uint8Array }>(this.db, 'SELECT bytes FROM work_exports WHERE id = ?', id),
      `export: ${id}`,
    );
    if (bytes.length !== row.byteCount || hashBytes(bytes) !== row.contentHash)
      throw new WorkspaceConflictError(
        'This saved Word file failed its integrity check. It has not been downloaded.',
      );
    return { record: unpack(row), bytes };
  }
}
