import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { bodyHash, groupHash } from './hash';
import { repoContentSource } from './repo';
import { SHIPPED_ROOTS, type ContentSource } from './source';

/**
 * The generated manifest's shape. `files` carries one hash per shipped
 * file (frontmatter-stripped body); `groups` carries the per-directory
 * hashes `.content-versions.json` records, with their content-version
 * dates, so a vault can tell "changed upstream" from "unchanged" without
 * re-reading the shipped tree.
 */
export interface ContentManifest {
  /** The plugin VERSION the manifest was generated from. */
  version: string;
  files: Record<string, { hash: string }>;
  groups: Record<string, { contentVersion: string; hash: string }>;
}

/** Shipped files hashed as text (frontmatter-stripped). Everything else is bytes. */
export function isText(path: string): boolean {
  return /\.(md|txt|json|yaml|yml)$/.test(path);
}

export function buildManifest(pluginRoot: string, source: ContentSource = repoContentSource(pluginRoot)): ContentManifest {
  const version = readFileSync(join(pluginRoot, 'VERSION'), 'utf8').trim();
  const versions = JSON.parse(readFileSync(join(pluginRoot, '.content-versions.json'), 'utf8')) as Record<
    string,
    { 'content-version': string; hash: string }
  >;
  const files: Record<string, { hash: string }> = {};
  for (const root of SHIPPED_ROOTS) {
    for (const path of source.list(root)) {
      // Text is hashed like the Python does (frontmatter off); a binary is
      // hashed whole — there is no frontmatter in a .docx to strip.
      files[path] = { hash: isText(path) ? bodyHash(source.read(path)) : createHash('sha256').update(source.readBytes(path)).digest('hex') };
    }
  }
  const groups: Record<string, { contentVersion: string; hash: string }> = {};
  for (const key of Object.keys(versions).sort()) {
    groups[key] = { contentVersion: versions[key]!['content-version'], hash: groupHash(join(pluginRoot, 'knowledge', key)) };
  }
  return { version, files, groups };
}

const HEADER = `// GENERATED by \`bun run content:manifest\` (runtime/src/content/generate.ts). Do not edit.
// One hash per shipped file (frontmatter-stripped body, sha256) and the
// per-group hashes of .content-versions.json. A test compares this file to a
// fresh generation, so a content change without a regeneration fails CI.
`;

export function renderManifestModule(manifest: ContentManifest): string {
  return `${HEADER}import type { ContentManifest } from './generate';

export const MANIFEST: ContentManifest = ${JSON.stringify(manifest, null, 2)};
`;
}

/** Shipped files the runtime reads at start that are NOT content (they
 * sit in `NOT_CONTENT`): doctor's law cadences. Embedded beside the content
 * and reachable through `embeddedExtra()`. */
export const EMBEDDED_EXTRAS: readonly string[] = ['knowledge/law/frontmatter-policy.json'];

/**
 * The embedded content module for the compiled binary (packaging spec
 * §3.2): one \`with { type: 'file' }\` import per shipped file (and per
 * extra), which Bun's \`--compile\` turns into an embedded asset. Written to
 * `runtime/src/generated/content-embed.ts` (git-ignored) by
 * `bun run build:runtime`; only the generated entry imports it, so a
 * checkout never type-checks against files a plugin install may lack. The
 * import paths are relative to `runtime/src/generated/`.
 */
export function renderEmbeddedModule(paths: string[], extras: readonly string[] = EMBEDDED_EXTRAS): string {
  const imports = paths.map((p, i) => `import f${i} from '../../../${p}' with { type: 'file' };`).join('\n');
  const entries = paths.map((p, i) => `  ${JSON.stringify(p)}: f${i},`).join('\n');
  const extraImports = extras.map((p, i) => `import x${i} from '../../../${p}' with { type: 'file' };`).join('\n');
  const extraEntries = extras.map((p, i) => `  ${JSON.stringify(p)}: x${i},`).join('\n');
  return `${HEADER}import { readFileSync } from 'node:fs';
import { isShippedPath, type ContentSource } from '../content/source';

${imports}
${extraImports}

const FILES: Record<string, string> = {
${entries}
};

/** Files read at start that are not content — see \`EMBEDDED_EXTRAS\`. */
export const extras: Record<string, string> = {
${extraEntries}
};

export function embeddedContentSource(): ContentSource {
  return {
    kind: 'embedded',
    list: prefix => Object.keys(FILES).filter(p => p === prefix || p.startsWith(\`\${prefix}/\`)).sort(),
    has: path => isShippedPath(path) && path in FILES,
    read: path => {
      const at = FILES[path];
      if (at === undefined) throw new Error(\`not shipped content: \${path}\`);
      return readFileSync(at, 'utf8');
    },
    readBytes: path => {
      const at = FILES[path];
      if (at === undefined) throw new Error(\`not shipped content: \${path}\`);
      return new Uint8Array(readFileSync(at));
    },
  };
}

export const content: ContentSource = embeddedContentSource();
`;
}

/** CLI: `bun runtime/src/content/generate.ts [--embedded <out.ts>]`. */
export async function main(argv: string[]): Promise<void> {
  const pluginRoot = resolve(import.meta.dir, '../../..');
  const manifest = buildManifest(pluginRoot);
  await Bun.write(join(import.meta.dir, 'manifest.ts'), renderManifestModule(manifest));
  const at = argv.indexOf('--embedded');
  if (at !== -1) {
    const out = argv[at + 1] ?? resolve(pluginRoot, 'runtime', 'src', 'generated', 'content-embed.ts');
    const paths = Object.keys(manifest.files);
    // A build that would embed nothing is a broken build, not a small one.
    if (paths.length === 0) throw new Error('refusing to generate an embedded module with zero shipped files');
    await Bun.write(resolve(out), renderEmbeddedModule(paths));
  }
  console.log(`content manifest: ${Object.keys(manifest.files).length} files, ${Object.keys(manifest.groups).length} groups, version ${manifest.version}`);
}

if (import.meta.main) await main(Bun.argv.slice(2));
