// GENERATED by `bun run content:manifest` (runtime/src/content/generate.ts). Do not edit.
// One hash per shipped file (frontmatter-stripped body, sha256) and the
// per-group hashes of .content-versions.json. A test compares this file to a
// fresh generation, so a content change without a regeneration fails CI.
import type { ContentManifest } from './generate';

export const MANIFEST: ContentManifest = {
  "version": "0.12.0",
  "files": {
    "knowledge/law/accessibility/_overview.md": {
      "hash": "36430c5756b08e9609b4d546b424c819c9c033a598f8df58713e2073c89bb595"
    },
    "knowledge/law/accessibility/ada-title-iii.md": {
      "hash": "ed57c72ff4a23995beaada6bb0346ea0dcfd70a097843fe5d00c621b4d4b0472"
    },
    "knowledge/law/accessibility/section-508.md": {
      "hash": "5d51ea4612b9a2be6a78361c57821a5890e8c7e93ab89fc44d7dd80322593ad7"
    },
    "knowledge/law/accessibility/state-accessibility.md": {
      "hash": "230421b4f9e0560bf1c8d4169c09906a1292215ba7260ccc60da4d5a9b68de3d"
    },
    "knowledge/law/accessibility/wcag.md": {
      "hash": "8d84b555319f7a4f0c7744b149469d9f74ef686b686af64120e4628c3833895b"
    },
    "knowledge/law/accessibility/website-accessibility.md": {
      "hash": "7b2f5189d8933b84c900a1a39a169f551281e42356a7b76f597161275b5f3b3e"
    },
    "knowledge/law/advertising-media/_overview.md": {
      "hash": "be5031666c1a148da64c5924dc84d9bd4c7e11607535b4b2f1d8a4573fae7aa1"
    },
    "knowledge/law/advertising-media/advertising-standards.md": {
      "hash": "57aeb282326cbb8cc30119d6f5f4de3ca789f6c3a155003ccb1a182be557ac9e"
    },
    "knowledge/law/advertising-media/content-licensing.md": {
      "hash": "6b85baee99cc6c01bc3ce9663fc641b9c5f792c62f7284fcdc05d687d2ac7218"
    },
    "knowledge/law/advertising-media/defamation.md": {
      "hash": "ef85bf04f7e5daaf995d393340db9c63e79854aa6d8db68cec57a6075affd9b2"
    },
    "knowledge/law/advertising-media/influencer-disclosures.md": {
      "hash": "a7c9c213a222fa45d13c52967410a3c809dff3437375313f8a2813d42890cf0e"
    },
    "knowledge/law/advertising-media/right-of-publicity.md": {
      "hash": "ba7bac368e5c2fa3918826b591deb1f09e3c9a459ee3041160e40716911d543b"
    },
    "knowledge/law/ai-and-automation/_overview.md": {
      "hash": "f011f0c0ce9015a343362d9afef8f5d11bdae90f37adc1cbacf8232ea9003fd7"
    },
    "knowledge/law/ai-and-automation/algorithmic-accountability.md": {
      "hash": "b0d25f248aa3ac5eb9cb938fcf5f2cf92b2e99ca72d0b897c4837de020a94716"
    },
    "knowledge/law/ai-and-automation/automated-decision-making.md": {
      "hash": "9205af20735ea48a1afbf85e6f72b4b305f68231efebb75eee797a2f576956ee"
    },
    "knowledge/law/ai-and-automation/deepfakes-synthetic-media.md": {
      "hash": "244f5008d406c8cbd83aed6b950a2d548ddc270b352494693fa794a46556baca"
    },
    "knowledge/law/ai-and-automation/eu-ai-act.md": {
      "hash": "9d47a62d65bc88d8c833a88d44f556f4c7d99181ab281393bb85977eedf2a23a"
    },
    "knowledge/law/ai-and-automation/model-ownership.md": {
      "hash": "7e7ec20a5168d50416723074681d3b04383507ddcfa3e117d0eaa92498c7b771"
    },
    "knowledge/law/ai-and-automation/training-data.md": {
      "hash": "97ead6d54d1a393b7348d8290d4a1f6db00e713622ca90acec204c383f99fcee"
    },
    "knowledge/law/ai-and-automation/us-state-ai-laws.md": {
      "hash": "595bcd51b587266641cd6db0c9ae564ebf658536c94c842f00f24a510fa26986"
    },
    "knowledge/law/antitrust/_overview.md": {
      "hash": "124993c5f628e6d08c2c07e46cdf0d7eed526fb8240216218e930b1af763b0c3"
    },
    "knowledge/law/antitrust/horizontal-restraints.md": {
      "hash": "906ee323b8316b427c339bf9c2641f7fcdc176438ebec54c052eba6fae6fdbee"
    },
    "knowledge/law/antitrust/merger-review.md": {
      "hash": "39d22db1090b754130b8aa5afb6c4c672e049fbcd282bfc26e611d65d6b88cf9"
    },
    "knowledge/law/antitrust/monopolization.md": {
      "hash": "e4698a27b971d22d2cdf7e349449ece7d8f9a4c96fcaa0ce97f01a602f24bb98"
    },
    "knowledge/law/antitrust/state-antitrust.md": {
      "hash": "a07f1102306e901f39a3be8ed7c7053791a43810e1522130b6d56742d5bf7dba"
    },
    "knowledge/law/antitrust/vertical-restraints.md": {
      "hash": "c380b31a3f60b720a78c673c1eb3a801aebe2f851fe198ca4e9ae88f6ceb1f3f"
    },
    "knowledge/law/bankruptcy-restructuring/_overview.md": {
      "hash": "a02507384903d735a369e03d2990107613221867de27d1fba25b5c0aa7a1deab"
    },
    "knowledge/law/bankruptcy-restructuring/automatic-stay.md": {
      "hash": "c1b3415241c21a12dc5f154ea4bd6798ac20dc611a8d603770f6b54c9c3f7e1f"
    },
    "knowledge/law/bankruptcy-restructuring/creditor-rights.md": {
      "hash": "f941a60ce723e3644e38879d78591703c5e278ab28774a40ff4f10b0c75b441f"
    },
    "knowledge/law/bankruptcy-restructuring/executory-contracts.md": {
      "hash": "2cf98c0ede309ff230a1bfaad5cbba6e2f93c5ffc988cce9638a952746d56dda"
    },
    "knowledge/law/bankruptcy-restructuring/ip-licenses-in-bankruptcy.md": {
      "hash": "4870d919bd8a3798c705e65f16d0587e3c839d2c9a16edd20fe336d32c202559"
    },
    "knowledge/law/bankruptcy-restructuring/preference-actions.md": {
      "hash": "569624d1bfc9e0ab94d08dc306b5c261a3b1bc82c5156c1603430e2cf46854d7"
    },
    "knowledge/law/bankruptcy-restructuring/safe-harbors.md": {
      "hash": "be8bdab13a50b20e7dd95f8f92951648dec611bcfeeeae8d090c87fa364353a3"
    },
    "knowledge/law/consumer-protection/_overview.md": {
      "hash": "238e82703aaa63cbaf4ca5d20715c2ec8a09a0979be2c480937fe4080c793cf2"
    },
    "knowledge/law/consumer-protection/auto-renewal.md": {
      "hash": "a80fda215494af72c57faab3f920ea6d875abdf09389abe968d3644e67728c64"
    },
    "knowledge/law/consumer-protection/can-spam.md": {
      "hash": "27ec602d29eabf33049ad94d72774c3ae2191a56c21c426880a42893f4d53c5f"
    },
    "knowledge/law/consumer-protection/dark-patterns.md": {
      "hash": "8ab3ac38d69ed525c6c9111cb4b9ffdd75443bcb9569ad94937ad68de69bef16"
    },
    "knowledge/law/consumer-protection/endorsements-testimonials.md": {
      "hash": "a635132fd494c5e77d285679942865d0935145995500eebfd8b99c86420197e2"
    },
    "knowledge/law/consumer-protection/ftc-udap.md": {
      "hash": "1c9760c1f936b60f4e489d3b277411cb9f444b3b722c92c7c7421765f0a9d920"
    },
    "knowledge/law/consumer-protection/magnuson-moss.md": {
      "hash": "c3b02d9eb5f69294347d65c820968dc85cd44684ecda793584dfaedafedf3edf"
    },
    "knowledge/law/consumer-protection/state-consumer-laws.md": {
      "hash": "3bcb101083ed828aae294e0fcb385e89bc5b8e5eb346db81e22c147f2eec986c"
    },
    "knowledge/law/consumer-protection/tcpa.md": {
      "hash": "c1da58d417907d2ca18eb723192912055dc2e6da3f1cdb07699b06c04456dfb2"
    },
    "knowledge/law/corporate/_overview.md": {
      "hash": "69cf68fa6ab37086f2985fc7df8c4013d62582855e0004338b98660550ba9b54"
    },
    "knowledge/law/corporate/dissolution-wind-down.md": {
      "hash": "97b682de2ff0ba89efd4d12524367ba1b09688ad3e8ac62c77c8d1355ebf2a36"
    },
    "knowledge/law/corporate/entity-formation.md": {
      "hash": "4a8add7970fd391dee66261c4be912fa15194d65941abd7be5789509d3d23fa4"
    },
    "knowledge/law/corporate/fiduciary-duties.md": {
      "hash": "657bd1c2ab9e16d30536d9431ccfd24e2bc606740d70c82e444ab30f89ae68e3"
    },
    "knowledge/law/corporate/governance.md": {
      "hash": "4da49b288112e2ab57be76e739bedfef66d98435d4166e59635fd0238b2d8e8a"
    },
    "knowledge/law/corporate/investment-transactions.md": {
      "hash": "5cadfafb42117b478961416f18d9a16d6acbc7a8e9c68995ab1a23ddec5653cc"
    },
    "knowledge/law/corporate/mergers-acquisitions.md": {
      "hash": "2e3fb510c94b0da6665ba0afe1d278a161ae87c498314f909c7ee3da0e4cef5b"
    },
    "knowledge/law/corporate/shareholder-agreements.md": {
      "hash": "88edadd317cce627cd1e3032a803cc0d6faff9b13aae68c2e9e41859ca89c5f1"
    },
    "knowledge/law/cybersecurity/_overview.md": {
      "hash": "e0e92513c84703c551a09a2d7b5ca05df8e02c4b64385ce559b9f8b4bc20e4cc"
    },
    "knowledge/law/cybersecurity/cmmc.md": {
      "hash": "93fb638c379ba920bbb88accc107a3eaec2e6972cca9199ddfe8e516a0dab679"
    },
    "knowledge/law/cybersecurity/incident-response.md": {
      "hash": "e8a189c35f6df0edc8777dc9873109e48617be76973d8ac27897e5b404044083"
    },
    "knowledge/law/cybersecurity/nist-frameworks.md": {
      "hash": "ed857cf675a1a156e5dbe4dbf36b365336f813266b070c6903942b9e89ec23dd"
    },
    "knowledge/law/cybersecurity/sec-cyber-disclosure.md": {
      "hash": "cfbb7241b9ecd6c3e57d3955676bd01444731ce068b61255e591941cb2e9375f"
    },
    "knowledge/law/cybersecurity/security-standards.md": {
      "hash": "c379ba96f1a68678e18bc4697df27e1826d9904d265e6840f9c4f97f7d2e68cc"
    },
    "knowledge/law/cybersecurity/state-breach-laws.md": {
      "hash": "ec84db0fd6bebfe1772597d553c057bd5e99ec54b3a7eea82be7f704925252bb"
    },
    "knowledge/law/data-privacy/_overview.md": {
      "hash": "aca6ff48c0db222bea38c26588d840aaa29e2f7d0220ea9c2fd90dc3536b70e1"
    },
    "knowledge/law/data-privacy/breach-notification.md": {
      "hash": "e2e2ed942cc9a232deccd9e6609031be52b0134b7f92e257f6ca09aefee343f4"
    },
    "knowledge/law/data-privacy/ccpa-cpra.md": {
      "hash": "9f7f1e0bc3cc5e5ff162dd559024947847e3219a48f21b499d04469406b68d7a"
    },
    "knowledge/law/data-privacy/consent-mechanics.md": {
      "hash": "c1a5c1fd2b5a8539cea2521e10be76e97926e0206ea42a271646023df76de63e"
    },
    "knowledge/law/data-privacy/coppa.md": {
      "hash": "e084b2c12645e97cb3aea264321f15297ccbb9e53aa4aeac877cbbdca1268429"
    },
    "knowledge/law/data-privacy/cross-border-transfers.md": {
      "hash": "01a551ea4e9a1d238357ba16d9af82c569d624a74433f8ddea8dd5fa54b203fb"
    },
    "knowledge/law/data-privacy/data-processing-agreements.md": {
      "hash": "0092969d3a33354f60cfea9e9fe55b3085944b5d868284d500321f4ec109e693"
    },
    "knowledge/law/data-privacy/data-subject-rights.md": {
      "hash": "4a143c083aebf7e0dec93a26e618681b2d5df8e354c2a7e0bd3606692590968a"
    },
    "knowledge/law/data-privacy/financial-sector-privacy-regulators.md": {
      "hash": "31f031e9ad446b92d2c2a6ed836c677c12e0f8cf112a71d020f5ab8ddc9b28ee"
    },
    "knowledge/law/data-privacy/gdpr.md": {
      "hash": "7742bb7d9e4adc9d8515a73769b1aedfc57574c1d87ab7142a308efb6e77f1b2"
    },
    "knowledge/law/data-privacy/glba-privacy.md": {
      "hash": "cafe41303a2fb34405ff953b2b341054f08386319628d2359ec44b66fac281b8"
    },
    "knowledge/law/data-privacy/international.md": {
      "hash": "bd0bc4501723f9abfe6657c667246921e612b97711748eb1b2095ff36713cfd6"
    },
    "knowledge/law/data-privacy/payments-data-localization.md": {
      "hash": "e367165070dd946bcc2af417b82a5dfab260f94f62241a24ee8c101e2b978964"
    },
    "knowledge/law/data-privacy/us-breach-notification-50-state.md": {
      "hash": "364f6c4501afec933705513d78bc82d2d05745a8bfc7547efda83ee3c64b332c"
    },
    "knowledge/law/data-privacy/us-eu-core.md": {
      "hash": "db24605afcbb12374e07baf91cc49b34871570638f308209311b5300fd0c60bd"
    },
    "knowledge/law/data-privacy/us-state-privacy.md": {
      "hash": "31b18d4ea3d2e7dbc94c027980dbcc1faaaa022901c601f553ae3e20dff14afa"
    },
    "knowledge/law/employment/_overview.md": {
      "hash": "b69b205eb905d56fec6a351a45e6284c5969d59c16dd191ca02f41ccfdb1fab8"
    },
    "knowledge/law/employment/at-will.md": {
      "hash": "db2fae462e2b8fc4f0d831cd61596ad0890247caba881574b07173df9c4b0fde"
    },
    "knowledge/law/employment/contractor-classification.md": {
      "hash": "0bb26464761662409cf8ab60729d8432652dda27ef4f2c0e49535155cf86ed82"
    },
    "knowledge/law/employment/discrimination-harassment.md": {
      "hash": "2cc85df94c271cf0490c4c4759ae58767b3dd3f9b65eaaf967f3e0c6030ea4ef"
    },
    "knowledge/law/employment/employee-benefits.md": {
      "hash": "4622a4137f2f704905050f940cb06bf0e37db3863c57facb30cbebb80c030a4d"
    },
    "knowledge/law/employment/immigration.md": {
      "hash": "15ec2edfd17c187857786ce7a66c1b40dfff24a5fca11823ef7265d9d73b4bd3"
    },
    "knowledge/law/employment/non-competes.md": {
      "hash": "ab7fa1e6f65d16a34e3a302de230c1dfc4f76f2bbc453b7b1f0a7a1ae8f46a2c"
    },
    "knowledge/law/employment/severance.md": {
      "hash": "122c8d0c50fdc663e2bc019ba576d7de6f9fcfcecbc43051e6ac2dfbcd3bff31"
    },
    "knowledge/law/employment/wage-and-hour.md": {
      "hash": "a3985e013355a9158e698edfc5cba625677c622e8ac8389de73b97cb7f7df021"
    },
    "knowledge/law/employment/workplace-safety.md": {
      "hash": "fca221d692bf9e1993744055f1e02482a9de1fbc188caf7fbc99342fb402feff"
    },
    "knowledge/law/environmental-esg/_overview.md": {
      "hash": "e9782a3e5fa3fe6b1621332e277c38623d1ae937094378cb0a3864b574746d7f"
    },
    "knowledge/law/environmental-esg/climate-disclosure.md": {
      "hash": "ea841e27c52597d3784a51cc5e46b935b5ef7aec64befbaaaccc82a7b8c9fbc2"
    },
    "knowledge/law/environmental-esg/environmental-due-diligence.md": {
      "hash": "ac90cc3aba54281879ac2f27c2deaa418285e244d7400328f35b99444ed96fdf"
    },
    "knowledge/law/environmental-esg/environmental-liability.md": {
      "hash": "4859f2bf592807338caf39f6a3cb66f7029e669485952d2b6ff1733f7f67f0da"
    },
    "knowledge/law/environmental-esg/esg-reporting.md": {
      "hash": "171ce8874d80af6a68412c22509a4cd226846572b460c3bf9147eb4278e427ed"
    },
    "knowledge/law/environmental-esg/sustainability-representations.md": {
      "hash": "adc563b7ac691f97424dd1d61febbd760240ea470c83773e46f2ba89c3aa8cd8"
    },
    "knowledge/law/financial-services/_overview.md": {
      "hash": "05999a38d44716697365a220bb23a198c8e0cf4568ead15aa9fd95eb06f88d76"
    },
    "knowledge/law/financial-services/banking-regulation.md": {
      "hash": "fcef781bab28b7dc090f376c3e6754ce383ba90904f0c62899cfd6c638c5ea58"
    },
    "knowledge/law/financial-services/card-network-ach-rules.md": {
      "hash": "0f878b6d60823d6cb9dc118cc465b255d1a6f7a1cb98b8c494046bc64aabbc61"
    },
    "knowledge/law/financial-services/cryptocurrency.md": {
      "hash": "855e3eb7e62bb842978a93d3852a5f5f0ce16e40a12b538310bff4de7d2e58e1"
    },
    "knowledge/law/financial-services/federal-payments-regulation.md": {
      "hash": "4b53ea6df2702c0727b248a9797977948c062eadcd919bc02967b145fd43a0d1"
    },
    "knowledge/law/financial-services/fintech.md": {
      "hash": "4fbdef00b9b707e3e26f8a2918d8bd0dac0fa16eb59750e724330c4734ca7494"
    },
    "knowledge/law/financial-services/kyc-aml.md": {
      "hash": "a6518e444d3870650f9cc5b00132803ac47394bcee219809d7999668e4c1f7b3"
    },
    "knowledge/law/financial-services/lending.md": {
      "hash": "90d9c1fe31580c9469a4178b85c12354799db7cde92bbccff01ee94c469110a6"
    },
    "knowledge/law/financial-services/payments-money-transmission.md": {
      "hash": "609d2e569b6463028323a2d894c78518b5b50fcf08c1263142d0104f9413f11d"
    },
    "knowledge/law/financial-services/pci-dss.md": {
      "hash": "59b93450f6444df1ba6c5977d7c9537d04aff797f237e1c406314f01e7d2c1e4"
    },
    "knowledge/law/financial-services/state-mtl-requirements.md": {
      "hash": "fe9a8390e18b73e5326afb5aa00e76c865ba0abd24dbeb3152dc29c4b20b34fa"
    },
    "knowledge/law/franchise/_overview.md": {
      "hash": "4967f2689fde4209914f85ba8b6fd69d735f339b8d1d6ffc18eaa3e1e2f2b048"
    },
    "knowledge/law/franchise/franchise-agreements.md": {
      "hash": "add86cd3ef1070ec6c43a24feed0494104ba367f6116b907ecbd7f4b49308979"
    },
    "knowledge/law/franchise/ftc-franchise-rule.md": {
      "hash": "f44d5ced5fbd0aef5dd5f8bd6fc828231154620468191f060db852466d223f2f"
    },
    "knowledge/law/franchise/relationship-laws.md": {
      "hash": "eb4adc36c5cb2bea48410b79c08c4942025a323753fde7b71c67cc36bc599a3f"
    },
    "knowledge/law/franchise/state-franchise-laws.md": {
      "hash": "bfcbf98e1a57bcfbd2a44c80993e22eb3295d5a5ab159a4a2d40c2c74170a556"
    },
    "knowledge/law/government-contracts/_overview.md": {
      "hash": "70b452573becf2f3c400a97e05b9ea1b8dfd9f223b38fccd418490dfe453f77b"
    },
    "knowledge/law/government-contracts/compliance-certifications.md": {
      "hash": "5e6b0d4e1d69999db4f17fd98a77f1d5970ce1060ed65c239095d977d38117ec"
    },
    "knowledge/law/government-contracts/far-dfar.md": {
      "hash": "aec9b8b8e8c67d384c382e88f2267f8d21db1adbc0754748013033350a022e08"
    },
    "knowledge/law/government-contracts/foia.md": {
      "hash": "c6b487fa5858d345cba65fb2657a38868fdb4d3f522196f6838dd4ad305cde9e"
    },
    "knowledge/law/government-contracts/procurement.md": {
      "hash": "bd8817f6a8c0cee6ee20bed7922500daa7dbec95065b1334122d345e9b3dba45"
    },
    "knowledge/law/government-contracts/small-business.md": {
      "hash": "3e9458f14b3cda12343398a605c57823c17917450e175cdbd8b93c4d7874bf4a"
    },
    "knowledge/law/government-contracts/sovereign-immunity.md": {
      "hash": "d63a1d79dbf6f07f970fa1cbf18a4ba554a8df99c61ecb75434b875258a8e428"
    },
    "knowledge/law/healthcare/_overview.md": {
      "hash": "0eb8d7e9b8f539d17dd47003a1e2641aa6512e343b36b3a201be203477f4b519"
    },
    "knowledge/law/healthcare/anti-kickback.md": {
      "hash": "055a779617a0822449017ee253f064e3016ca40d8a3538b46945a8f7e519a306"
    },
    "knowledge/law/healthcare/fda-regulation.md": {
      "hash": "3e48723b57141b20b6b13a335c935d95737ebc222162d5e96f8851dae14c0d7e"
    },
    "knowledge/law/healthcare/hipaa-compliance.md": {
      "hash": "a4349842cd8a28a2f3ecdc9e50506294ce3f29a7895763ac2aa751a76e1255ca"
    },
    "knowledge/law/healthcare/provider-agreements.md": {
      "hash": "2e6b33e59df9c2c320370ca17a27e8c8087fda11ab90f013ff0afe2c1d78d4fb"
    },
    "knowledge/law/healthcare/stark-law.md": {
      "hash": "e24ca1810ced33e0ae122246c04975b022e7306ea61dd42261be1844c466da1a"
    },
    "knowledge/law/healthcare/telehealth.md": {
      "hash": "b4f85329ace2d92d9ad0120089463994b42d504550b0551cee7e3af821dcf266"
    },
    "knowledge/law/insurance/_overview.md": {
      "hash": "90a1e05fe353282192fe4800548c5d363b41114b33536cfc45ff8a8c4d1d110c"
    },
    "knowledge/law/insurance/claims-procedures.md": {
      "hash": "c627b5e5fc052346cc04feb7600c2a616a82dd094748af47a6826985b7dee70c"
    },
    "knowledge/law/insurance/commercial-general-liability.md": {
      "hash": "06fd8e41a641ba8ac7303729bfda116feb95712ac84fa18349b6288ab87c3c00"
    },
    "knowledge/law/insurance/coverage-analysis.md": {
      "hash": "55bb527b1097523b231347b3a7c55564d19ccca40841d63bbffc5085213a3f93"
    },
    "knowledge/law/insurance/cyber-liability.md": {
      "hash": "cd023fc7889a412b6c6670d56f8621b951c521e35bed8280cb25e2d496cab36b"
    },
    "knowledge/law/insurance/directors-officers.md": {
      "hash": "6ee07a2066ee4112954eaff17c5d56e5a83cbef18198d97b9e4826c31b7159b0"
    },
    "knowledge/law/insurance/employment-practices.md": {
      "hash": "d5172b28e95f232a8475fb8d321bfb96e4b79db56a5bd8d6dea0a4d40897789e"
    },
    "knowledge/law/insurance/professional-liability.md": {
      "hash": "fa8988d6f9010373f83435711d564de5c7a662a0c53af4e855456d2a33bc8e2f"
    },
    "knowledge/law/international-trade/_overview.md": {
      "hash": "fdbcd928669a30ef582098efbb0337545aa27ea5608fdd870d51672c1eb96e59"
    },
    "knowledge/law/international-trade/anti-boycott.md": {
      "hash": "9a5c70d45963b62e17143a4a1df8e5018c6d0a1ce27d42337bad6f433018fb5f"
    },
    "knowledge/law/international-trade/anti-corruption.md": {
      "hash": "e7358d6ac9614654d0ef2e440c8c43803741cbce690d7dc75bad3f260120a079"
    },
    "knowledge/law/international-trade/customs.md": {
      "hash": "e6331f0a52d99a3aab614e0621c14a9d27c736cb8f940cde32bf334a5d42eaca"
    },
    "knowledge/law/international-trade/export-controls.md": {
      "hash": "eb44214ea16b48ad831d4b33bf1afc3b35cc1b1bb64179597192848be9700ff1"
    },
    "knowledge/law/international-trade/foreign-investment.md": {
      "hash": "1eb5d9bcaa43df7a65d3190b093e1c9b4778a2db55dc1cf991c5b546d5318728"
    },
    "knowledge/law/international-trade/sanctions.md": {
      "hash": "9962318a04cffd1d6a1a039c0170adf8ac933775e78d148f1597014524913950"
    },
    "knowledge/law/ip-and-technology/_overview.md": {
      "hash": "8694404dcbc6ba78671ee120bcf1365a7ad7b52bb65bd6108c88aee1e5b9ba45"
    },
    "knowledge/law/ip-and-technology/copyrights.md": {
      "hash": "9d0e59159a61b793d022121d96a31cf0dcf65a7e121095f4afe15f5f1f76bae4"
    },
    "knowledge/law/ip-and-technology/domain-names.md": {
      "hash": "73b79c05aa6e569a7af35fe9cfdaa7b608e13c3dab2ba410a2894093e755d6da"
    },
    "knowledge/law/ip-and-technology/open-source.md": {
      "hash": "b83df9f064beda8f66351570415f32afbac963dcb8264c5bc13c0b54900e6737"
    },
    "knowledge/law/ip-and-technology/patents.md": {
      "hash": "597ca332d5b19d3fb80777562e0ddce16d38899b885dd5127a088e623dab894f"
    },
    "knowledge/law/ip-and-technology/saas-technology.md": {
      "hash": "6f416ea74b40976f76273e6562285c36d34106a9280fd7a0586ad2f889630bc6"
    },
    "knowledge/law/ip-and-technology/trade-secrets.md": {
      "hash": "91e34140b840b3de850f1ed8121218abd6c8e25326f6d9f3bcd3679964a73fd3"
    },
    "knowledge/law/ip-and-technology/trademarks.md": {
      "hash": "274d119bbefa24157101605408bb410c99840b77d88de0db39d8c6e96f0218cc"
    },
    "knowledge/law/labor-relations/_overview.md": {
      "hash": "dc4100f2a516c0e512a8174d72527a82d26aaf4a69d71bd83c0f246dbcc4f1ef"
    },
    "knowledge/law/labor-relations/collective-bargaining.md": {
      "hash": "e0a1c480581361748b4696e3c2d4756c81267876e47e10dd044781ad7b80d770"
    },
    "knowledge/law/labor-relations/nlra.md": {
      "hash": "50212718f341cb009093f3c5ce0292be1617ced730b25ac58f93a7c98c6a2e0d"
    },
    "knowledge/law/labor-relations/strikes-lockouts.md": {
      "hash": "c81ad178b852b16cbd47d012f8598eccbe25627f66d51cced74a8c07fb551756"
    },
    "knowledge/law/labor-relations/union-organizing.md": {
      "hash": "e0a7acbb488c1c2a83c5c48b2a150c80566ae593d57cf5e3e21fd8c919b273fb"
    },
    "knowledge/law/litigation/_overview.md": {
      "hash": "70cc17536863aaac13f1fecce37d851748040a7368249b922b253a9d785a5a8b"
    },
    "knowledge/law/litigation/arbitration.md": {
      "hash": "9ed2f3fb726c1555420e51a3b16c73caa2a66dd911152d3f7a493f7293a69988"
    },
    "knowledge/law/litigation/class-actions.md": {
      "hash": "5003c30cabb38f09567cfb514b2d5236e4ba5df58ac099f34e705dff3041e647"
    },
    "knowledge/law/litigation/demand-letters.md": {
      "hash": "4aeb26b7b3c2c348d6d49430c52ec2edaad68930732b87753413e259585f0a10"
    },
    "knowledge/law/litigation/e-discovery.md": {
      "hash": "d27d2aaeb1a1e772065579450920c77ac7933b9edd595652d15ce1b78062cdb7"
    },
    "knowledge/law/litigation/litigation-holds.md": {
      "hash": "85611415aa3b630a825b54ce9e4fc8b1c9780bd6c661c12306627649c0aabb8c"
    },
    "knowledge/law/litigation/privilege.md": {
      "hash": "8b99a43981fb81be143d91abb7f7c1e4e810a40429b071f0d300e27f5e0b3e73"
    },
    "knowledge/law/litigation/regulatory-inquiries.md": {
      "hash": "9a7f68fb96ceec9510cc5b3093b6d1dd1ccd2920f1e470d2e8996e28e8dbe554"
    },
    "knowledge/law/litigation/settlement.md": {
      "hash": "1d829bcfd38144b2173b51c7e4600ab4d5ee2a7ce2516a2d740663745f751265"
    },
    "knowledge/law/litigation/subpoenas.md": {
      "hash": "b60d3ce282c49a221d8d9a8f7e277ba59015beeed372033934d59f97ef45e417"
    },
    "knowledge/law/nonprofit/_overview.md": {
      "hash": "c885086f98ceb3f07fed5a05cddb3bd9f52c0b589d782aba4b7c4e257920b56e"
    },
    "knowledge/law/nonprofit/charitable-solicitation.md": {
      "hash": "ad21517ff871d6a74bf4efc75f4a5d3dad9259dfffe16e67d58aecdeb6d610b1"
    },
    "knowledge/law/nonprofit/donor-restrictions.md": {
      "hash": "1f35828c93c891fbb794d534bfe8efd11d48355a0622cda96af9cc2f0aa41d53"
    },
    "knowledge/law/nonprofit/nonprofit-governance.md": {
      "hash": "69992e17db59b10dd4c0dd18b30c849fa8988e2cdb34a81c8fffe16801c9ff8e"
    },
    "knowledge/law/nonprofit/tax-exempt-status.md": {
      "hash": "febb9cf0a3cc22f853885644f36cca532233fe5a4b8fecbd9f80a278b4ee3d9e"
    },
    "knowledge/law/nonprofit/unrelated-business-income.md": {
      "hash": "85313d06543e57ee571b438ca0bed790b12018d1398ea8d23e72b8c03481c15c"
    },
    "knowledge/law/product-counseling/_overview.md": {
      "hash": "e7e0dd838b0c7f363eac98c532becbc7073a79d3bb2def7aacdc585d4a8a502a"
    },
    "knowledge/law/product-counseling/consumer-product-safety.md": {
      "hash": "b85f6550b1585e2afc9e71da410439ce3415012432212f4aa939b2f8db99a192"
    },
    "knowledge/law/product-counseling/product-liability.md": {
      "hash": "0f9799b27b5d93b011a745fbc912ea1d7c17307a5ec3de50445db23d274520e3"
    },
    "knowledge/law/product-counseling/recalls.md": {
      "hash": "44a05118c5574c15ff5cbbab958a1498a4935464bbee45216b3814c832180591"
    },
    "knowledge/law/product-counseling/warnings-labels.md": {
      "hash": "8f7f1243f9bede0f468d852a56fe75d59b5ce5f2080098f69ba71654b1bf8942"
    },
    "knowledge/law/real-estate/_overview.md": {
      "hash": "3f1ce3bbdfeb9dc89d0e155df83b88293e6afcd8de73c3f30d88b0dd0616fe63"
    },
    "knowledge/law/real-estate/commercial-leases.md": {
      "hash": "2727a3eb772777a1a98bd3a020113afb321b06ea1509de495b81c428b842ab4e"
    },
    "knowledge/law/real-estate/construction.md": {
      "hash": "0c86b2761ea297f774d4496f1069d34766ab72ce73ad38181238622b0b22628b"
    },
    "knowledge/law/real-estate/easements-encumbrances.md": {
      "hash": "0b03d2417f216820fffe1328dea43a8073aee5ad139c0260cd4f6537e51f2182"
    },
    "knowledge/law/real-estate/environmental-covenants.md": {
      "hash": "cad43a7e0b8f1120b46cf56f9118e2f38aeb9f75a00411ffa993b6a55cf7da51"
    },
    "knowledge/law/real-estate/real-estate-transactions.md": {
      "hash": "8400020f5093ea45feac1611f4d11d607477793532d58921363d4400501bdb06"
    },
    "knowledge/law/real-estate/zoning-land-use.md": {
      "hash": "8cfa994691669004cc4ab9865e5172ae097b0818e12c59e910493359a4c856d2"
    },
    "knowledge/law/securities/_overview.md": {
      "hash": "51a95db7c09a25d40fa62b91ea73e74b5fd01dfe7ed868935892f4b9b8e8b1cd"
    },
    "knowledge/law/securities/blue-sky-laws.md": {
      "hash": "f20d7667d04b43b33515db90423df8aadafd8aa8145ab47a3e91013f64f1b3de"
    },
    "knowledge/law/securities/crowdfunding.md": {
      "hash": "ffbc300e7b87de7bf73cdd9783d02dc1d16963d909a9cbafac3d818af0e349ea"
    },
    "knowledge/law/securities/equity-issuance.md": {
      "hash": "94071b88b38ae89c6e6e5642b4038fb05b9579f560d0e13c83fc71d3d0ad9787"
    },
    "knowledge/law/securities/exemptions.md": {
      "hash": "00f3c5db6fb268274c748d70a765167de788cbd46732abfad80b636836f7aabc"
    },
    "knowledge/law/securities/insider-trading.md": {
      "hash": "a809f5d8b1428a954b1e7ad94b6002cb5d109da272dbd5d202a557f5efe703e8"
    },
    "knowledge/law/securities/investment-advisers.md": {
      "hash": "eaf9e95c05abc3df5c546e5c41e2ef9e0cc6e975d25ffcc61d64d0c0f8e52a8a"
    },
    "knowledge/law/securities/public-company.md": {
      "hash": "8d6b5b41de47f495a5de339ee6f56268953386b6c0cb657ec83de0296e0aae58"
    },
    "knowledge/law/tax/_overview.md": {
      "hash": "3eab221a503ad6e909003b9d9ff72ecf71278997af7fd1e5659d62b59d4b7b08"
    },
    "knowledge/law/tax/equity-compensation-tax.md": {
      "hash": "252b0b9855f4d17cc7b48dce0f076409829bb464e7ed9c085d7479f9fd2eec77"
    },
    "knowledge/law/tax/international-tax.md": {
      "hash": "bb38902ce6b3a67ea6b5b8e32e8916c9bbf12bf6c0b05635d63b04b116c31d2c"
    },
    "knowledge/law/tax/sales-tax-vat.md": {
      "hash": "084105bfcaa3d69bf33671f7b67829004b59e412e1584d0a34a32ab4c882f8a3"
    },
    "knowledge/law/tax/tax-indemnities.md": {
      "hash": "27ad21587c5ce84ec6d0b1a23c68e7f355d886eb501d4f86871ed7077308d106"
    },
    "knowledge/law/tax/transfer-pricing.md": {
      "hash": "c97812e09428c2c588667c44e261316b331ac4b428e21ccb1fe3a293f3588be1"
    },
    "knowledge/law/tax/withholding.md": {
      "hash": "46ed09fa1610eccdd61e0d2b263e677eb4b693f698a6e4d8af55f4daa6321c6b"
    },
    "knowledge/law/white-collar-investigations/_overview.md": {
      "hash": "64ccc0e05dc5e5943f37c6ab7ef71ce131e073bb48722650c259fb1f21cf4141"
    },
    "knowledge/law/white-collar-investigations/corporate-compliance-programs.md": {
      "hash": "00459e3d99b2a4a2953ba1c2240603538de17a39482bb389574293195be74178"
    },
    "knowledge/law/white-collar-investigations/doj-cooperation.md": {
      "hash": "3b57643bd591b1c6b510323c33bfbe8c3facb6ed5ce19821b5e036083d28c8a2"
    },
    "knowledge/law/white-collar-investigations/fcpa-enforcement.md": {
      "hash": "833510bd92ed629a87a34dd4cc661fea3c118d0e50fd648b5fae3a7e29b9912d"
    },
    "knowledge/law/white-collar-investigations/internal-investigations.md": {
      "hash": "1e2724f7b478eaffabd0ddfb9a441f21fceda42fddafe823307c33f6743f4b18"
    },
    "knowledge/law/white-collar-investigations/whistleblower.md": {
      "hash": "f0ad4ded78fac6b720799f4b8003255302d7359ef3194d7d993745250ed56c8f"
    },
    "knowledge/practice-seed/library/_index.md": {
      "hash": "5b2c55f4dc7a81121177ac41a17e8c39b3e10ccbd772f7afaea3e420525fe269"
    },
    "knowledge/practice-seed/library/acceptable-use.md": {
      "hash": "c40119007d62d48f5e866950fcb16b300d591bdbc785d731db34a788d9200ace"
    },
    "knowledge/practice-seed/library/ai-and-data-use.md": {
      "hash": "6c829f6119d76f1e91a4f0aa5986d8a0156521a184acd3c8ff3fabb47d8a7fd8"
    },
    "knowledge/practice-seed/library/assignment-and-change-of-control.md": {
      "hash": "f451ef1e7ee8bea34847cb551eefe2fdfcefb4348ddb06f675b1013d88526d5a"
    },
    "knowledge/practice-seed/library/audit-rights.md": {
      "hash": "619ac0de54ab614bdce6f87bd5956dd8638fcd66fabebbbe6884e47e202bf034"
    },
    "knowledge/practice-seed/library/boilerplate.md": {
      "hash": "a95ec6dcc8cab484f1201cb6cde80afa022481fbd7e1bc1736942bad0db04c10"
    },
    "knowledge/practice-seed/library/compliance-regulatory.md": {
      "hash": "ff697d40f9c95451b3755c370711312db706f55caf0866c51168ac6514597c60"
    },
    "knowledge/practice-seed/library/data-protection.md": {
      "hash": "21c9131ce12476af36ec5ead824f689a840a4ff7499f6011f9431b0c4d90a892"
    },
    "knowledge/practice-seed/library/dispute-resolution.md": {
      "hash": "e60e058f662abac1b7b7cc650a4736ba136061d9cb01dfddb9e1fea1f7c94d48"
    },
    "knowledge/practice-seed/library/force-majeure.md": {
      "hash": "8ec2605c4df95459224e9a3ea1c932e61dc3e8c901f173675af4bea108c9485a"
    },
    "knowledge/practice-seed/library/governing-law-jurisdiction.md": {
      "hash": "c7c1f8fa3db8da013f1ce185feaca62015d9b8e2300f6fb94cd5f4a1e60550aa"
    },
    "knowledge/practice-seed/library/insurance-requirements.md": {
      "hash": "03d371e1899aafb151a031e58db967b32d393618692700a64293bccdb4c9277c"
    },
    "knowledge/practice-seed/library/ip-and-confidentiality.md": {
      "hash": "7477f17de6037317b0f24af7b572c0b88efef2d9bea4fc299e76a8921c63da1d"
    },
    "knowledge/practice-seed/library/liability-and-indemnification.md": {
      "hash": "23526aab2216fdf8727d811b7e02252bf1ca386a0bef1596ec94379e7a505f25"
    },
    "knowledge/practice-seed/library/most-favored-nation.md": {
      "hash": "1219608e6358fbbf2c877ba8c26786bce28fb85cd0edb04e480b80bf53b918a3"
    },
    "knowledge/practice-seed/library/non-solicitation.md": {
      "hash": "de5be5aa7859db04bb040e42071eafca9b7523113dd80b653134662ce66dc19d"
    },
    "knowledge/practice-seed/library/notices.md": {
      "hash": "4e044c2b55cec35b4957fe7459b71eb13ceaf97a01de127f4bfeb6ba825eb70b"
    },
    "knowledge/practice-seed/library/sla-and-performance.md": {
      "hash": "342835853bcede74924d0f60e7c6bb5ac0d9ab0ecccd776c945f0b2424c78e12"
    },
    "knowledge/practice-seed/library/source-code-escrow.md": {
      "hash": "4fcfae67abc38a298dcce0fbfbb6ffc267ff71d78ef2b92b482a3f3945f1ae91"
    },
    "knowledge/practice-seed/library/termination-and-renewal.md": {
      "hash": "02f2408058aa744863c1ba3d18137a4c0f66a40773d63dbe946c37a18cebbe1d"
    },
    "knowledge/practice-seed/library/transition-assistance.md": {
      "hash": "9c70588cbb302d61f9ce50e214760cbfd1606d5fc050d2b473addc08acf18817"
    },
    "knowledge/practice-seed/library/warranties-disclaimers.md": {
      "hash": "d79b2a391832cf6b44bfe446b461fcee703d33d0cb94bd795b4cc032e6f4554b"
    },
    "knowledge/practice-seed/methods/ai-governance.md": {
      "hash": "ad1cab9ca28d781cb4c116317eb948f62a32810762591979a92ad1993a8481a3"
    },
    "knowledge/practice-seed/methods/amendment-drafting.md": {
      "hash": "841228643eb33f885eb537dc969dad38a90c23a59b61a363ff52b396cfee1c6a"
    },
    "knowledge/practice-seed/methods/board-and-governance.md": {
      "hash": "5a8f4a0c04a23a5a7568a2f242ca4daed12f75fe8675f107e7cc62da0627d5f7"
    },
    "knowledge/practice-seed/methods/compliance-assessment.md": {
      "hash": "ad46b9aca31ed986ae4fda63f567ecc8e5bcea98b0e9e18cb9748070107938e3"
    },
    "knowledge/practice-seed/methods/consumer-facing-terms.md": {
      "hash": "ed9fd15a9cec89d46e6462841814d852bd501fea68a859274f91f9f276146652"
    },
    "knowledge/practice-seed/methods/contract-review.md": {
      "hash": "d4427e586b6ea9f1699e91770ec24d88a15dd09982c344a494222185068e180e"
    },
    "knowledge/practice-seed/methods/dispute-response.md": {
      "hash": "e6ca3d4ffd05919242f7b1a6d9d2351fbed1c2ae526f6f242b348e51582e35d4"
    },
    "knowledge/practice-seed/methods/due-diligence.md": {
      "hash": "98fd68ed41adaa9075a7022d5791554c4529c746487c27b89efe21dd25da6563"
    },
    "knowledge/practice-seed/methods/employment-agreement.md": {
      "hash": "621800abe0c9441a40b023cea027ff1f5ebffec165163e34a49d83b8c50f2c94"
    },
    "knowledge/practice-seed/methods/employment-termination.md": {
      "hash": "d02d1656436e606c0484345ee6d1a780d6fd4d1598faba5651b86048b0c28c2f"
    },
    "knowledge/practice-seed/methods/equity-compensation.md": {
      "hash": "7e0e20bebcbfced541087f63515c1b8615d3368f50873747d09be24a77755084"
    },
    "knowledge/practice-seed/methods/financing-round.md": {
      "hash": "a113d6f8a4cf529bc364056efd7d8ba536f1e4cfb565b2c988d73bbcedee6c51"
    },
    "knowledge/practice-seed/methods/government-contract.md": {
      "hash": "7e15f165b5d043a4cfc823cf9208f93dd79ee2734bb68cd98074461857ce7bff"
    },
    "knowledge/practice-seed/methods/healthcare-baa.md": {
      "hash": "5a5cb8589416571aa0e42cb7faf1700719d73b6b260fcdae5f8dd66ee7350502"
    },
    "knowledge/practice-seed/methods/index.md": {
      "hash": "a98e527e701a45ddd1b4cb454ff70f553a50cebef7e535c5665323a9a0d7ef8c"
    },
    "knowledge/practice-seed/methods/ip-assignment.md": {
      "hash": "ca3937c9872327bc03fed5846b975199138440a4ac8ee608c0c01d8d9c30bea0"
    },
    "knowledge/practice-seed/methods/ip-portfolio-management.md": {
      "hash": "180c42adeec228575fb59e6a2b9d610c0bc7721fe0a03cb9507dd3e3583c4a48"
    },
    "knowledge/practice-seed/methods/legal-memo.md": {
      "hash": "ab62635119cf608600fd9fa784e4b2e9c09d9f33bacc02356a31d2bba7457699"
    },
    "knowledge/practice-seed/methods/litigation-hold.md": {
      "hash": "06ed4853633493493cc3a7915985f294496e8f30567dfec5a1832b67ae6ebc72"
    },
    "knowledge/practice-seed/methods/ma-integration.md": {
      "hash": "32e986f212ce6fa4db5035d8be5f684a47a5917b549c29def8a7a142b44fcb7e"
    },
    "knowledge/practice-seed/methods/ma-transaction.md": {
      "hash": "b0b52bb86cd66c9ad03ff8cb519d67040b0ec99f563c6579bce7b05cc4d5a110"
    },
    "knowledge/practice-seed/methods/marketing-ad-review.md": {
      "hash": "4a57e8dd5b10c599040e938f2e4a365aee6b5bd37c52d3dadf1f018986c8a379"
    },
    "knowledge/practice-seed/methods/nda-screening.md": {
      "hash": "c953fe4c9c4c4fb41dd35f2c6d5acecfe03bbe94075c19d6e8ead58190db8484"
    },
    "knowledge/practice-seed/methods/nda-triage.md": {
      "hash": "11dad1a1e517527c8f6710d7b0868b276c2f299e078d6c3a48f0de2553af9994"
    },
    "knowledge/practice-seed/methods/negotiation.md": {
      "hash": "0dc14416bfc5b6d46101cee01753b7ae897dbd6fecf1a78500fee015d6e55e42"
    },
    "knowledge/practice-seed/methods/open-source-compliance.md": {
      "hash": "ba61919100743f67f9b8c93203bb57bf5a7688efeb678acd16109237ebab6d31"
    },
    "knowledge/practice-seed/methods/partner-terms.md": {
      "hash": "252a19db403d99ee5e3c78a1c94529deb4ac2c4bf235a60f37bc9a67ec9b9ef3"
    },
    "knowledge/practice-seed/methods/policy-drafting.md": {
      "hash": "f61cf6ce706844650a94ac5f8a2ea000e10c81c8cb1f3ebcf6cadbd970c7ea60"
    },
    "knowledge/practice-seed/methods/privacy-compliance-program.md": {
      "hash": "d7a6cbe5f75ddff7e931ee7b774f7e6291681c71f0b1bc5cae8a6c093edd93c0"
    },
    "knowledge/practice-seed/methods/privacy-dpa.md": {
      "hash": "514039245ad905cbf4516fc675f8633637bb8b17c4571f110d6a9ea297ecbce4"
    },
    "knowledge/practice-seed/methods/real-estate-lease.md": {
      "hash": "e6e4fa7a638ee0725639692cddc460362fdefb702f9ba13b4f0e0f73410ec631"
    },
    "knowledge/practice-seed/methods/regulatory-response.md": {
      "hash": "84c74d5a802dabf8e712222f30e47822ae4923fca8dd955436b2a1471adf9888"
    },
    "knowledge/practice-seed/methods/saas-agreement.md": {
      "hash": "803ba12070a8090323ebc2c66fd0cc5f839bff9cf262242eddfa556c3b3db110"
    },
    "knowledge/practice-seed/methods/security-incident-response.md": {
      "hash": "34b48f54d12cebbe8700c8258a1a8b39cd8169ea04b13a1f2f5d574cde633feb"
    },
    "knowledge/practice-seed/methods/trade-compliance-screening.md": {
      "hash": "804ea4c8a58feeeeb8649cdef349498628969856e93c8b7a09b65dc463281d0b"
    },
    "knowledge/practice-seed/methods/vendor-onboarding.md": {
      "hash": "36ef62dae96a64d13ba402b86f68fc878045cfd57f66b5063aedcf3f6e219280"
    },
    "knowledge/practice-seed/profile.md": {
      "hash": "4a92e948850fe74d690cd78d90c0c9d657183079a6c7904d1caff93077d22e5f"
    },
    "knowledge/practice-seed/reference/_index.md": {
      "hash": "044a2455e34a79f6d767d8d2f5e08d51a52df3e23f0b965050bce366d88f8d2b"
    },
    "knowledge/practice-seed/standards/acceptable-use.md": {
      "hash": "1b24fe57b4e09e2245fdbd20034b795488d31a41fec47aeafd0fc6e0dc5110d7"
    },
    "knowledge/practice-seed/standards/ai-data-use.md": {
      "hash": "37b3d6f38bd59a43f537184c6db4f64181395c1d94a5a49f3f4e873f1aa4f750"
    },
    "knowledge/practice-seed/standards/assignment-change-of-control.md": {
      "hash": "c48f1fd074a464930e41e53b39929faba5a447deed116e223d31f880a06fd7da"
    },
    "knowledge/practice-seed/standards/audit-rights.md": {
      "hash": "d875e919601891925a0968a20a5481e641f88055bf9261ece797ce12df0ce6da"
    },
    "knowledge/practice-seed/standards/compliance-certifications.md": {
      "hash": "6365b8f25b2c973a779660926191054349b5ddd7e1ab9e8d6030721981abf5fd"
    },
    "knowledge/practice-seed/standards/confidentiality.md": {
      "hash": "682b57b3e095cc74fa2c6f4b8f2d25e4d4891a3a85b252a1f8473f05901ffbf1"
    },
    "knowledge/practice-seed/standards/data-protection.md": {
      "hash": "dc46e26d46d6a0dc89dd88e15eb8c070b7ba3d11322c0d27297772b7dab85269"
    },
    "knowledge/practice-seed/standards/dispute-resolution.md": {
      "hash": "d6f9e804ef5029fe5b28fc77141010e443aa874f258880d64b66b0fb6916b671"
    },
    "knowledge/practice-seed/standards/fees-payment.md": {
      "hash": "fe60a907cfb56c62bc3e1fe4d154ced8fbf0274db6a824535fcab9693c865467"
    },
    "knowledge/practice-seed/standards/force-majeure.md": {
      "hash": "d5d83bfe68788ffaab2fa1c80ef42089d0ca6810d377505e71691b94f9cf3275"
    },
    "knowledge/practice-seed/standards/indemnification.md": {
      "hash": "583a84104e3011a52462dbfec4be914d85fe24f5cf81e883e483afdc43ca57a9"
    },
    "knowledge/practice-seed/standards/index.md": {
      "hash": "1126768e666a7c71a585d2c0cba41cb3b4a3aadb5bee3baa82b93c7d3d717db6"
    },
    "knowledge/practice-seed/standards/insurance-requirements.md": {
      "hash": "f69e6eba4fcde78da46ef1a4d7ea2d26101a2ad42f07d7540d9fc393dd83c7b0"
    },
    "knowledge/practice-seed/standards/ip-ownership.md": {
      "hash": "ae73515a2e03d3ba6bd7982ae65973232c7916f331c27de1476b4a0fd8303815"
    },
    "knowledge/practice-seed/standards/limitation-of-liability.md": {
      "hash": "33a2d7f089f6795ae9f8847f609260b84e89730ac85f47177f136ca02e7d7c3d"
    },
    "knowledge/practice-seed/standards/most-favored-nation.md": {
      "hash": "3b1dcba9ceae3a87b489da53f165646763380b7b9ff0643b955bf44949804444"
    },
    "knowledge/practice-seed/standards/non-solicitation.md": {
      "hash": "74b3f1ed4b94dbadc91b7c326d10486cdc24673bb4e0cb5bb506131f443d43cc"
    },
    "knowledge/practice-seed/standards/notices.md": {
      "hash": "54b30e4ea32f971e12f51353b3e726174adf8fd388eda21cab68e2d397ea0def"
    },
    "knowledge/practice-seed/standards/representations-warranties.md": {
      "hash": "de5b2a013e293be2837cf0dd08290cc0ebe7ef6738d0ba85115804b3ecddcdd1"
    },
    "knowledge/practice-seed/standards/service-levels.md": {
      "hash": "2590ec3d0f8784f154128a529ed91f70ba65392dbabf2a2e2cc90f4d369624f2"
    },
    "knowledge/practice-seed/standards/source-code-escrow.md": {
      "hash": "bed2208ec65515fb3ddf037a9d9c22ae718237a5e4fd9cc4f79338fb925adbea"
    },
    "knowledge/practice-seed/standards/subcontractors-subprocessors.md": {
      "hash": "84c1accd89809c56526780a75a106e9a4d87f4e0f124a1c4724a0956a4c7ec56"
    },
    "knowledge/practice-seed/standards/termination-renewal.md": {
      "hash": "1d991b1b3a265e116bf69918b2ed938da1ee603f047ffde46e8dfaf129be7f0f"
    },
    "knowledge/practice-seed/standards/transition-assistance.md": {
      "hash": "fc460d356e69a3175ef48bd6bef0161546c3f4a547b0187993f2d53b392d39f0"
    },
    "knowledge/practice-seed/standards/warranties-disclaimers.md": {
      "hash": "280991dea2a5e86500805be5023ffce88d24e5e17269467358e1b6c2c5919d8f"
    },
    "templates/memory/patterns.md": {
      "hash": "e1fdfa347fd6c588cb80a82cb3f8976bca16230a2c58767ab4ce3ff9c16da987"
    },
    "primitives/draft.md": {
      "hash": "7054ab415c5a2ce9c7dba1ff4e62add9babc3a4ad6ff12a19767baabe7d0d220"
    },
    "primitives/evaluate.md": {
      "hash": "2d832826117b04e90197a054aad436389a5e7233fe8061f6f0460dd6564a39a4"
    },
    "primitives/read.md": {
      "hash": "8c1ced1bddee04c799cec94ec1f7528dd44c6c50fdd13bd43b5e9085dcd18bf3"
    },
    "primitives/redline-output.md": {
      "hash": "7009e713971a97a36b95d1a856b530bc3eea06978e8a65a3614f3956fe453eff"
    },
    "primitives/remember.md": {
      "hash": "2125beb53f6072aca69a8bb720b7ed5478abc15951f911e6ab36c9ddeaafab66"
    },
    "primitives/research.md": {
      "hash": "a7aa8f6e808a17e7de8687d4948cdd49c1d094e2fe76283d788c199498c6ad14"
    },
    "skills/counsel/SKILL.md": {
      "hash": "7e8cb06ea00596bd3be5f768f4529a198ebbe3b654b9b639f51607eb023c0cbd"
    },
    "skills/retro/SKILL.md": {
      "hash": "4975a92a57f7a4f6c9c1c81495f3b92a462a04e60fa197d7278b29bcd0675eff"
    },
    "skills/demo/assets/sample-mutual-nda.docx": {
      "hash": "67025b706197311c96327e35df6401d78135b330567ecde92131067f405bd6e5"
    },
    "skills/demo/assets/sample-mutual-nda.md": {
      "hash": "0072b329826d5ea2297b8c786ba0b54bef092ab1c5c646874bd90569030f9624"
    }
  },
  "groups": {
    "law/accessibility": {
      "contentVersion": "2026-06-11",
      "hash": "c7fe46c772bda68ddbda8b46a17dabe2f3890630979f89fadea3efc06e892081"
    },
    "law/advertising-media": {
      "contentVersion": "2026-06-11",
      "hash": "ceff705c81f7b8228f57aff2b737e5d487d5874a1b88fdc43f50246b37fb6d97"
    },
    "law/ai-and-automation": {
      "contentVersion": "2026-06-10",
      "hash": "1f3cc9648d64655adb6de20c951ae014e91aeff1027cef45347e01f60ae9f4f7"
    },
    "law/antitrust": {
      "contentVersion": "2026-06-11",
      "hash": "973d069905cb1523534ab5b6dbb87d94088e754ea5d782f452ebacdf117f0407"
    },
    "law/bankruptcy-restructuring": {
      "contentVersion": "2026-06-11",
      "hash": "44bcd5419d8f930b01963356eaafca18dbe12e5c1a595c8dc60b25491af59620"
    },
    "law/consumer-protection": {
      "contentVersion": "2026-06-11",
      "hash": "b93bdf020c2f173ca3102910af3d32c229fc9c39c59a012b9adf2687c36bf0ab"
    },
    "law/corporate": {
      "contentVersion": "2026-06-10",
      "hash": "6aabfac6222b4393533c1feceb3e0803fccf9079fa8f9ccd6c7675422f737b1c"
    },
    "law/cybersecurity": {
      "contentVersion": "2026-06-11",
      "hash": "1f05489965059a99afe61affef13ab1705bdddc815716d4f286781d8292483c8"
    },
    "law/data-privacy": {
      "contentVersion": "2026-06-11",
      "hash": "e4e6548533cae423f54d17460d379f00fb09ad3423e51b0ffa2ae206a5080467"
    },
    "law/employment": {
      "contentVersion": "2026-06-11",
      "hash": "3a7e974d3aa9a36918c0112a29ef2c833aebc67697e83c93d3901dffcf702b28"
    },
    "law/environmental-esg": {
      "contentVersion": "2026-06-11",
      "hash": "247c004e415bdbc6e1dd164fa28269ae415705b8072b6d38367288f25e90ceb0"
    },
    "law/financial-services": {
      "contentVersion": "2026-06-11",
      "hash": "96b9cbaab76d1cc4ca7865a9d9007da1056ffe465c9edc6ebb71cc6afa471026"
    },
    "law/franchise": {
      "contentVersion": "2026-06-11",
      "hash": "857973c3a748e7d689b4b1496c0244a0272741bcf0297163541843fdf79af8d2"
    },
    "law/government-contracts": {
      "contentVersion": "2026-06-11",
      "hash": "658f5ee16a68e4f4e9c68fda9b5a9da4b004efbc5c48eff739fb4dc2b62e7117"
    },
    "law/healthcare": {
      "contentVersion": "2026-06-11",
      "hash": "638b20c850919d987234579b4f5599711b88ab4adc1311280688e877792348c1"
    },
    "law/insurance": {
      "contentVersion": "2026-06-11",
      "hash": "46a45edcbcba49dbc80a1b798b05f00fc01b8599e8ff3a57c84cf379e64524cc"
    },
    "law/international-trade": {
      "contentVersion": "2026-06-11",
      "hash": "994ab03e128d0a0db59dea78266017037d880bd24bd5d483e3b6c91325d5b18b"
    },
    "law/ip-and-technology": {
      "contentVersion": "2026-06-11",
      "hash": "dd28bb7a2c584798b89e8c51881ca6a886a1c45ef6df46e71621a04d8780dc08"
    },
    "law/labor-relations": {
      "contentVersion": "2026-06-11",
      "hash": "6b7051de5257a790c9d604dd9a80c8fb2537333ef1ca3700364ce789867ad59e"
    },
    "law/litigation": {
      "contentVersion": "2026-06-11",
      "hash": "a4e787691812cc87276efc811ea41e518f9125da2fe5100543059729b5641a27"
    },
    "law/nonprofit": {
      "contentVersion": "2026-06-11",
      "hash": "714844e7b2e272e625b00584f096671f49b908f9f3a434d37c5adb81700dcd4a"
    },
    "law/product-counseling": {
      "contentVersion": "2026-06-11",
      "hash": "3b9308760dd6f35560ee935a6045e1000cf23fdfad81e13f3c0e6f0dd26beacf"
    },
    "law/real-estate": {
      "contentVersion": "2026-06-11",
      "hash": "8c28d0ec467208e35ee94b928a989675915e442f5a09918e3631225231ad102d"
    },
    "law/securities": {
      "contentVersion": "2026-06-11",
      "hash": "782dc76ae1aa877c0d8f1b4c2d40dd363cdab1737c78f2541ceea95b2eb70a4a"
    },
    "law/tax": {
      "contentVersion": "2026-06-11",
      "hash": "79602cb248de6110579ccdf8c847a5f1a3fc9c4cebd247f9fec1f5102179fbc3"
    },
    "law/white-collar-investigations": {
      "contentVersion": "2026-06-11",
      "hash": "728124a46490284be9ee6f0687d7337b7e90a7c62141325272ce1d0057655433"
    },
    "practice-seed/library": {
      "contentVersion": "2026-06-11",
      "hash": "e200f74f68e8c2a94a7969e0bc0056363d13439cc0dff3da1b794433ab571996"
    },
    "practice-seed/methods": {
      "contentVersion": "2026-06-11",
      "hash": "0277174f6fb14d5a38b6677e6917e72f05f81e7f5d3c401b8600127c90c5f51e"
    },
    "practice-seed/reference": {
      "contentVersion": "2026-06-10",
      "hash": "37843a5b423deb088d14a12e9ac32eb7a90c5a762e2223313d2740d9e96cc159"
    },
    "practice-seed/standards": {
      "contentVersion": "2026-06-11",
      "hash": "ea84417569839d4756081fda97af72ace0e8abc4ab90569aad137b16712f6768"
    }
  }
};
