"""Own-entity setup, exact signing boundaries and chat receipts. Synthetic only."""
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

BASE = 'http://127.0.0.1:7461'
OUT = Path(__file__).parent / '.tmp' / 'workspace'
OUT.mkdir(parents=True, exist_ok=True)
with sync_playwright() as p:
    browser = p.chromium.launch()
    context = browser.new_context(viewport={'width': 1440, 'height': 1050}, reduced_motion='reduce')
    page = context.new_page()
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    headers = {'Authorization': 'Bearer workspace-browser-test-only'}
    def api(path='', body=None):
        response = context.request.get(BASE + '/api/workspace' + path, headers=headers) if body is None else context.request.post(BASE + '/api/workspace' + path, headers=headers, data=body)
        assert response.ok, response.text()
        return response.json()
    def shot(name):
        for width in [390, 1440]:
            page.set_viewport_size({'width': width, 'height': 1050})
            page.evaluate('window.scrollTo(0, 0)')
            page.evaluate('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))')
            assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
            page.screenshot(path=str(OUT / f'{name}-{width}.png'), full_page=False)
    page.goto(BASE + '/#token=workspace-browser-test-only')
    page.wait_for_load_state('networkidle')
    page.goto(BASE + '/#/knowledge?section=preferences&view=entities')
    directory = page.get_by_role('region', name='Entities and signatories', exact=True)
    expect(directory).to_be_visible()
    directory.get_by_role('button', name='Add entity', exact=True).click()
    dialog = page.get_by_role('dialog', name='Edit signing entity', exact=True)
    dialog.get_by_label('Legal name', exact=True).fill('Example Test LLC')
    dialog.get_by_label('Notice address', exact=True).fill('100 Synthetic Street\nTest City')
    dialog.get_by_label('Aliases, one per line', exact=True).fill('Example US\n')
    dialog.get_by_role('button', name='Save changes', exact=True).click()
    expect(dialog).to_have_count(0)
    expect(directory.get_by_role('heading', name='Example Test LLC', exact=True)).to_be_visible()
    assert not api('/entity-registry')['availableToChats']
    for name in ['Synthetic Alex', 'Synthetic Casey']:
        directory.get_by_role('button', name='Add signatory', exact=True).click()
        person = page.get_by_role('dialog', name='Edit signatory', exact=True)
        person.get_by_label('Name', exact=True).fill(name)
        person.get_by_role('button', name='Save changes', exact=True).click()
        expect(person).to_have_count(0)
        expect(directory.get_by_role('heading', name=name, exact=True)).to_be_visible()
    directory.get_by_role('button', name='Add signing rule', exact=True).click()
    rule = page.get_by_role('dialog', name='Edit signing rule', exact=True)
    rule.get_by_label('Rule name', exact=True).fill('Routine vendor authority')
    rule.get_by_label('Signatory', exact=True).select_option(label='Synthetic Alex')
    rule.get_by_role('checkbox', name='Example Test LLC', exact=True).check()
    rule.get_by_role('checkbox', name='Vendor agreements', exact=True).check()
    rule.get_by_label('Value condition', exact=True).select_option('limited')
    rule.get_by_label('Maximum amount', exact=True).fill('100000')
    rule.get_by_label('Currency', exact=True).fill('USD')
    rule.get_by_label('What value counts?', exact=True).select_option('total')
    shot('signing-rule-editor')
    rule.get_by_role('button', name='Save changes', exact=True).click()
    expect(rule).to_have_count(0)
    expect(directory).to_contain_text('Up to and including USD 100000')
    directory.get_by_role('button', name='Add signing rule', exact=True).click()
    rule.get_by_label('Rule name', exact=True).fill('Fallback authority')
    rule.get_by_label('Signatory', exact=True).select_option(label='Synthetic Casey')
    rule.get_by_role('checkbox', name='Example Test LLC', exact=True).check()
    rule.get_by_role('checkbox', name='Vendor agreements', exact=True).check()
    rule.get_by_label('Value condition', exact=True).select_option('fallback')
    rule.get_by_role('button', name='Save changes', exact=True).click()
    expect(rule).to_have_count(0)
    expect(directory).to_contain_text('Fallback authority')
    assert len(api('/conversations')) == 0

    directory.locator('.entity-check > summary').click()
    checker = directory.locator('.entity-check')
    checker.get_by_label('Signing entity', exact=True).select_option(label='Example Test LLC')
    checker.get_by_label('Agreement type', exact=True).select_option('vendor')
    checker.get_by_label('Agreement value', exact=True).fill('100000.00')
    checker.get_by_label('Agreement currency', exact=True).fill('USD')
    checker.get_by_label('Value basis', exact=True).select_option('total')
    checker.get_by_role('button', name='Check signing rules', exact=True).click()
    expect(checker).to_contain_text('Suggested signatory: Synthetic Alex')
    checker.get_by_label('Agreement value', exact=True).fill('100000.01')
    checker.get_by_role('button', name='Check signing rules', exact=True).click()
    expect(checker).to_contain_text('Suggested signatory: Synthetic Casey')
    checker.get_by_label('Agreement value', exact=True).fill('')
    checker.get_by_role('button', name='Check signing rules', exact=True).click()
    expect(checker).to_contain_text('Signing details need clarification')
    assert not api('/entity-registry')['availableToChats']
    shot('entity-directory')

    directory.get_by_role('button', name='Make available to chats', exact=True).click()
    expect(directory).to_contain_text('Available to chats')
    registry = api('/entity-registry')
    assert api()['profile'] is None or not api()['profile']['applyToChats']
    entity_id = registry['entities'][0]['id']
    page.get_by_role('button', name='New chat', exact=True).click()
    page.get_by_role('textbox', name='Message Counsel OS', exact=True).fill('signatory fixture ' + entity_id)
    page.get_by_role('button', name='Send message', exact=True).click()
    receipt = page.get_by_role('region', name='Recorded signing-rule check', exact=True)
    expect(receipt).to_contain_text('Suggested signatory: Synthetic Alex')
    expect(page.locator('.chat-turn')).to_contain_text('Saved in conversation', timeout=15000)
    page.get_by_role('button', name='View context', exact=False).first.click()
    page.get_by_role('button', name='Latest response', exact=True).click()
    entities = page.get_by_label('Entity directory context', exact=True)
    entities.locator('summary').first.click()
    expect(entities).to_contain_text('Example Test LLC · Details read')
    entities.get_by_text('Exact saved details', exact=True).click()
    expect(entities).to_contain_text('100 Synthetic Street')
    page.get_by_role('button', name='Close context', exact=True).click()
    shot('signing-check-chat')
    page.reload()
    expect(receipt).to_contain_text('Suggested signatory: Synthetic Alex')
    assert not errors, errors
    browser.close()
    print('PASS: entity/signatory/rule forms; blank-field preservation; inclusive/over-limit/unknown checks; opt-in sharing; no setup model calls; chat read/check receipts; desktop/mobile/reload')
