"""Matter hierarchy and durable outputs; fresh --chat fixture, synthetic data only."""
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

BASE = 'http://127.0.0.1:7461'
with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    page = browser.new_page(viewport={'width': 1440, 'height': 1000}, reduced_motion='reduce')
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.goto(BASE + '/#token=workspace-browser-test-only')
    page.wait_for_load_state('networkidle')
    print('Navigation:', page.get_by_role('complementary', name='Workspace navigation').inner_text())
    nav = page.get_by_role('navigation')
    expect(nav.get_by_role('link', name='Work', exact=True)).to_have_count(0)
    page.goto(BASE + '/#/matters')
    page.get_by_role('link', name='Document assessment', exact=False).filter(has=page.locator('.row-copy')).first.click()
    matter_url = page.url
    expect(page.get_by_role('heading', name='The matter at a glance')).to_be_visible()
    page.get_by_role('button', name='Edit brief', exact=True).click()
    dialog = page.get_by_role('dialog', name='Edit matter brief')
    dialog.get_by_label('Background and purpose', exact=True).fill('Synthetic notice assessment for this matter.')
    dialog.get_by_label('Open questions', exact=True).fill('Who receives the notice?')
    dialog.get_by_label('Next steps', exact=True).fill('Confirm the recipient.')
    dialog.get_by_role('button', name='Save brief', exact=True).click()
    expect(dialog).to_have_count(0)
    expect(page.locator('.matter-hub-aside')).to_contain_text('Who receives the notice?')
    page.reload()
    expect(page.locator('.matter-hub-aside')).to_contain_text('Confirm the recipient.')
    page.get_by_role('link', name='Ask about this matter', exact=True).click()
    page.get_by_role('textbox', name='Message Counsel', exact=True).fill('Discuss the notice question.')
    page.get_by_role('button', name='Send message', exact=True).click()
    expect(page.get_by_text('Saved in conversation', exact=True)).to_be_visible(timeout=15000)
    chat_url = page.url
    page.get_by_role('button', name='Save as output', exact=True).click()
    dialog = page.get_by_role('dialog', name='Save as output')
    dialog.get_by_label('Output title', exact=True).fill('Synthetic notice assessment')
    dialog.get_by_label('Type', exact=True).select_option('assessment')
    dialog.get_by_role('button', name='Save output', exact=True).click()
    expect(dialog).to_have_count(0)
    page.get_by_role('link', name='Open output: Synthetic notice assessment', exact=True).click()
    expect(page.get_by_role('heading', name='Synthetic notice assessment', exact=True)).to_be_visible()
    page.get_by_role('link', name='Open originating conversation', exact=True).click()
    expect(page.get_by_role('link', name='Open output: Synthetic notice assessment', exact=True)).to_be_visible()
    page.goto(matter_url)
    page.get_by_role('button', name='Conversations', exact=True).click()
    expect(page.locator('.matter-chat-list')).to_contain_text('Discuss the notice question.')
    page.get_by_role('button', name='Outputs', exact=True).click()
    expect(page.locator('.matter-view')).to_contain_text('Synthetic notice assessment')
    expect(page.locator('.matter-view')).not_to_contain_text('Discuss the notice question.')
    page.get_by_role('button', name='Documents', exact=True).click()
    expect(page.locator('.matter-view')).to_contain_text('Synthetic agreement extraction')
    page.get_by_role('button', name='Decisions', exact=True).click()
    expect(page.get_by_role('heading', name='Recorded decisions', exact=True)).to_be_visible()
    page.get_by_role('button', name='Overview', exact=True).click()
    screenshots = Path(__file__).parent / '.tmp' / 'workspace'
    screenshots.mkdir(parents=True, exist_ok=True)
    page.screenshot(path=str(screenshots / 'matter-hub.png'), full_page=True)
    page.set_viewport_size({'width': 390, 'height': 844})
    expect(page.get_by_role('heading', name='The matter at a glance')).to_be_visible()
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
    page.screenshot(path=str(screenshots / 'matter-hub-mobile.png'), full_page=True)
    page.set_viewport_size({'width': 1440, 'height': 1000})
    page.get_by_role('button', name='New chat', exact=True).click()
    page.get_by_role('textbox', name='Message Counsel', exact=True).fill('An unassigned discussion to organize later.')
    page.get_by_role('button', name='Send message', exact=True).click()
    expect(page.get_by_text('Saved in conversation', exact=True)).to_be_visible(timeout=15000)
    page.get_by_role('button', name='Add to a matter', exact=True).click()
    dialog = page.get_by_role('dialog', name='Organize into a matter')
    dialog.get_by_label('Matter name', exact=True).fill('Started in conversation')
    dialog.get_by_role('checkbox').check()
    dialog.get_by_role('button', name='Organize conversation', exact=True).click()
    expect(dialog).to_have_count(0)
    page.locator('.scope-name').get_by_role('link', name='Started in conversation', exact=True).click()
    expect(page.locator('.matter-chat-list')).to_contain_text('An unassigned discussion to organize later.')
    assert not errors, errors
    browser.close()
    print('PASS: scoped conversations, editable brief, named output/backlink, documents, decisions, persistence, mobile layout')
