"""In-place drafting, working preferences and distinct chat history. Synthetic fixture only."""
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

BASE = 'http://127.0.0.1:7461'
OUT = Path(__file__).parent / '.tmp' / 'workspace'
OUT.mkdir(parents=True, exist_ok=True)
with sync_playwright() as p:
    browser = p.chromium.launch()
    context = browser.new_context(viewport={'width': 1440, 'height': 1000}, reduced_motion='reduce')
    page = context.new_page()
    errors, model_requests = [], []
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.on('request', lambda req: model_requests.append(req) if req.method == 'POST' and req.url.endswith('/practice-drafting') else None)
    headers = {'Authorization': 'Bearer workspace-browser-test-only'}
    def api(path='', body=None):
        response = context.request.get(BASE + '/api/workspace' + path, headers=headers) if body is None else context.request.post(BASE + '/api/workspace' + path, headers=headers, data=body)
        assert response.ok, response.text()
        return response.json()
    def shot(name):
        for width in [390, 1440]:
            page.set_viewport_size({'width': width, 'height': 844 if width == 390 else 1000})
            assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
            page.screenshot(path=str(OUT / f'{name}-{width}.png'), full_page=True)

    page.goto(BASE + '/#token=workspace-browser-test-only')
    page.wait_for_load_state('networkidle')
    page.goto(BASE + '/#/knowledge')
    print('Practice controls:', page.locator('main button').all_text_contents())
    original_count = len(api()['knowledge'])
    page.get_by_role('button', name='Add to practice', exact=True).click()
    dialog = page.get_by_role('dialog', name='Add to practice', exact=True)
    dialog.get_by_label('Title', exact=True).fill('My original wording')
    dialog.get_by_label('What should we remember?', exact=True).fill('My existing draft.')
    dialog.get_by_role('button', name='Help me draft this', exact=True).click()
    expect(dialog.locator('.draft-assist')).to_contain_text('scripted-fixture')
    assert not model_requests
    dialog.get_by_label('What would you like to say?', exact=True).fill('Express my preference for surgical NDA edits.')
    shot('practice-inline-helper')
    dialog.get_by_role('button', name='Draft into form', exact=True).click()
    expect(dialog.get_by_role('button', name='Save for review', exact=True)).to_be_disabled()
    expect(dialog.get_by_label('Title', exact=True)).to_have_value('Synthetic NDA review approach')
    expect(dialog.get_by_label('Practice item type', exact=True)).to_have_value('method')
    expect(dialog).to_contain_text('Nothing has been saved.')
    assert len(api()['knowledge']) == original_count
    assert len(api('/conversations')) == 0
    dialog.get_by_role('button', name='Undo suggestion', exact=True).click()
    expect(dialog.get_by_label('Title', exact=True)).to_have_value('My original wording')
    expect(dialog.get_by_label('What should we remember?', exact=True)).to_have_value('My existing draft.')
    dialog.get_by_label('What would you like to say?', exact=True).fill('fixture failure')
    dialog.get_by_role('button', name='Draft into form', exact=True).click()
    expect(dialog).to_contain_text('Your form is unchanged.')
    expect(dialog.get_by_label('Title', exact=True)).to_have_value('My original wording')
    dialog.get_by_label('What would you like to say?', exact=True).fill('Refine it again.')
    dialog.get_by_role('button', name='Draft into form', exact=True).click()
    dialog.get_by_role('button', name='Stop drafting', exact=True).click()
    expect(dialog).to_contain_text('Drafting stopped.')
    expect(dialog.get_by_label('What should we remember?', exact=True)).to_have_value('My existing draft.')
    dialog.get_by_role('button', name='Save for review', exact=True).click()
    expect(dialog).to_have_count(0)
    assert len(api()['knowledge']) == original_count + 1

    page.goto(BASE + '/#/knowledge?section=preferences&view=documents')
    page.get_by_role('button', name='Set review preferences', exact=True).click()
    prefs = page.get_by_role('region', name='Working preferences editor', exact=True)
    expect(prefs).to_be_visible()
    prefs.get_by_label('General document review', exact=True).fill('Preserve document structure.')
    prefs.get_by_label('NDA review instructions', exact=True).fill('Make surgical NDA edits; use comments for material changes.')
    page.goto(BASE + '/#/home')
    page.goto(BASE + '/#/knowledge?section=preferences&view=documents')
    expect(prefs.get_by_label('NDA review instructions', exact=True)).to_have_value('Make surgical NDA edits; use comments for material changes.')
    prefs.get_by_label('Changes and comments attributed to', exact=True).select_option('custom')
    prefs.get_by_label('Word author name', exact=True).fill('Synthetic Avery')
    prefs.get_by_label('Word filename pattern', exact=True).fill('{document}_{variant}_{author}')
    prefs.get_by_role('button', name='Save working preferences', exact=True).click()
    expect(prefs).to_contain_text('New responses will use these preferences')
    version_one = api('/working-preferences')
    assert version_one['version'] == 1
    page.get_by_role('button', name='View saved preferences', exact=True).click()
    expect(page.get_by_role('region', name='Saved document preferences', exact=True)).to_contain_text('Make surgical NDA edits')
    shot('saved-document-preferences')
    page.get_by_role('button', name='Edit working preferences', exact=True).click()
    shot('working-preferences')
    # An external edit cannot be silently replaced by this form.
    api('/working-preferences', {**{key: version_one[key] for key in ['generalReview', 'ndaReview', 'authorMode', 'customAuthor', 'filenamePattern']}, 'generalReview': 'External update.', 'expectedRevisionId': version_one['revisionId']})
    prefs.get_by_label('General document review', exact=True).fill('Stale local update.')
    prefs.get_by_role('button', name='Save working preferences', exact=True).click()
    expect(prefs).to_contain_text('another window')
    expect(prefs.get_by_label('General document review', exact=True)).to_have_value('Stale local update.')
    page.once('dialog', lambda d: d.accept())
    prefs.get_by_role('button', name='Reload saved preferences', exact=True).click()
    expect(prefs.get_by_label('General document review', exact=True)).to_have_value('External update.')

    page.get_by_role('button', name='New chat', exact=True).click()
    expect(page.get_by_role('textbox', name='Message Counsel', exact=True)).to_have_value('')
    expect(page.get_by_role('region', name='Conversation history', exact=True)).to_have_count(0)
    page.get_by_role('textbox', name='Message Counsel', exact=True).fill('Synthetic preference context check.')
    page.get_by_role('button', name='Send message', exact=True).click()
    expect(page.locator('.chat-answer')).to_contain_text('Synthetic adapter test')
    page.get_by_role('button', name='View context', exact=False).first.click()
    page.get_by_role('button', name='Latest response', exact=True).click()
    receipt = page.get_by_label('Working instructions included', exact=True)
    expect(receipt).to_contain_text('version 2')
    receipt.locator('summary').click()
    expect(receipt).to_contain_text('Make surgical NDA edits')
    page.get_by_role('button', name='Close context', exact=True).click()
    page.locator('nav').get_by_role('link', name='Chats', exact=True).click()
    history = page.get_by_role('region', name='Conversation history', exact=True)
    expect(history).to_contain_text('Synthetic preference context check.')
    expect(page.get_by_role('textbox', name='Message Counsel', exact=True)).to_have_count(0)
    shot('conversation-history')
    page.get_by_role('textbox', name='Find a conversation', exact=True).fill('no match')
    expect(history).to_contain_text('No matching conversations')
    page.get_by_role('textbox', name='Find a conversation', exact=True).fill('preference')
    history.get_by_role('link', name='Synthetic preference context check.', exact=False).click()
    expect(page.locator('.chat-answer')).to_contain_text('Synthetic adapter test')
    assert not errors, errors
    browser.close()
    print('PASS: inline drafts/undo/stop/errors without premature saves, manual save, preferences/reload/conflicts/context, chat history/new chat, desktop/mobile')
