#!/usr/bin/env bun
// `bun run build:runtime [--target bun-darwin-arm64|bun-linux-x64] [--out <file>]`
//
// Builds the standalone `counsel-os` binary (packaging spec §3.1): the built
// UI and the shipped content are embedded through generated modules under
// runtime/src/generated/ (git-ignored), and a generated entry registers them
// before the CLI runs. The checkout never imports those files; only this
// build does.
import { mkdirSync, statSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dir, '..');
const args = Bun.argv.slice(2);
const flag = (name: string): string | undefined => {
  const at = args.indexOf(name);
  return at === -1 ? undefined : args[at + 1];
};
const target = flag('--target') ?? `bun-${process.platform === 'darwin' ? 'darwin' : process.platform}-${process.arch === 'arm64' ? 'arm64' : 'x64'}`;
const out = flag('--out') ?? resolve(root, 'dist', 'counsel-os');

async function run(cmd: string[], what: string): Promise<void> {
  const proc = Bun.spawn(cmd, { cwd: root, stdout: 'inherit', stderr: 'inherit' });
  if ((await proc.exited) !== 0) {
    console.error(`build:runtime: ${what} failed`);
    process.exit(1);
  }
}

// 1. The page, then its embed module.
try {
  statSync(resolve(root, 'runtime', 'ui', 'dist', 'index.html'));
} catch {
  await run(['bun', 'run', 'ui:build'], 'ui:build');
}
await run(['bun', 'scripts/gen_ui_embed.ts'], 'gen_ui_embed');

// 2. The content manifest + the embedded content module.
mkdirSync(resolve(root, 'runtime', 'src', 'generated'), { recursive: true });
await run(['bun', 'scripts/gen_content_manifest.ts', '--embedded', 'runtime/src/generated/content-embed.ts'], 'gen_content_manifest --embedded');

// 3. The entry that registers both and then runs the CLI.
await Bun.write(
  resolve(root, 'runtime', 'src', 'generated', 'entry.ts'),
  `// GENERATED by scripts/build_runtime.ts. Do not edit; git-ignored.
import { registerEmbedded } from '../core/embedded';
import { content, extras } from './content-embed';
import { ui } from './ui-embed';

registerEmbedded({ ui, content, extras });
await import('../cli');
`,
);

// 4. Compile.
mkdirSync(resolve(out, '..'), { recursive: true });
await run(['bun', 'build', '--compile', `--target=${target}`, 'runtime/src/generated/entry.ts', '--outfile', out], `bun build --compile (${target})`);
const size = statSync(out).size;
console.log(`built ${out} (${target}, ${(size / 1024 / 1024).toFixed(1)} MB)`);
