#!/usr/bin/env python3
"""gen_browse_reference — regenerate the Command Reference in skills/browse/SKILL.md.

Reads the real command registry from browse/src/commands.ts (the single source
of truth for browse command names: READ_COMMANDS, WRITE_COMMANDS,
META_COMMANDS) and pairs every command with usage and a one-line description
maintained below. The script fails if the registry and the docs disagree in
either direction — adding or removing a browse command forces a doc update —
and CI fails on any drift between this script's output and the committed
SKILL.md.

Usage:
    python3 scripts/gen_browse_reference.py            # rewrite SKILL.md in place
    python3 scripts/gen_browse_reference.py --check    # exit 1 if SKILL.md is stale
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
COMMANDS_TS = REPO_ROOT / "browse" / "src" / "commands.ts"
SKILL_PATH = REPO_ROOT / "skills" / "browse" / "SKILL.md"

BEGIN_MARKER = "<!-- commands:begin (generated by scripts/gen_browse_reference) -->"
END_MARKER = "<!-- commands:end -->"

REGISTRY_SETS = ("READ_COMMANDS", "WRITE_COMMANDS", "META_COMMANDS")

# Usage + descriptions are derived from the handlers in
# browse/src/{read,write,meta}-commands.ts and browse/src/snapshot.ts.
# Keep descriptions to one line; prose belongs in SKILL.md proper.
# Each entry: (command, usage, description). Groups are presentation only —
# membership is validated against the union of the registry sets.
GROUPS = [
    ("Navigation", [
        ("goto", "goto <url>",
         "Navigate to a URL. Waits for DOM content to load (15s timeout)."),
        ("back", "back",
         "Go back in browser history."),
        ("forward", "forward",
         "Go forward in browser history."),
        ("reload", "reload",
         "Reload the current page."),
        ("url", "url",
         "Print the current page URL."),
    ]),
    ("Content Extraction", [
        ("text", "text",
         "Extract the visible text of the page (scripts, styles, and SVG stripped)."),
        ("html", "html [selector]",
         "Full page HTML, or the innerHTML of a selector/ref."),
        ("links", "links",
         "List all links on the page as `text -> URL`."),
        ("forms", "forms",
         "List forms and their fields as JSON (password values redacted)."),
        ("accessibility", "accessibility",
         "Print the raw ARIA accessibility tree of the page."),
    ]),
    ("Snapshot & Compare", [
        ("snapshot", "snapshot [-i] [-c] [-d N] [-s sel] [-D] [-a] [-o path] [-C]",
         "Accessibility snapshot with `@e1`, `@e2`... refs for interaction. "
         "`-i` interactive elements only; `-c` compact; `-d N` limit depth; "
         "`-s sel` scope to a selector; `-D`/`--diff` diff against the previous snapshot; "
         "`-a` annotated screenshot (path via `-o`); `-C` find non-ARIA clickable elements as `@c` refs."),
        ("diff", "diff <url1> <url2>",
         "Navigate to each URL in turn and show a unified diff of their text content. "
         "To see what changed on the current page since your last snapshot, use `snapshot -D` instead."),
    ]),
    ("Interaction", [
        ("click", "click <selector>",
         "Click an element (CSS selector or `@e`/`@c` ref from `snapshot`)."),
        ("fill", "fill <selector> <value>",
         "Fill a form field. Use `\"\"` to clear it."),
        ("select", "select <selector> <value>",
         "Select an option from a dropdown."),
        ("hover", "hover <selector>",
         "Hover over an element (reveals tooltips and menus)."),
        ("type", "type <text>",
         "Type text via the keyboard at the current focus."),
        ("press", "press <key>",
         "Press a key (e.g. Enter, Tab, Escape)."),
        ("scroll", "scroll [selector]",
         "Scroll to the page bottom, or scroll an element into view."),
        ("wait", "wait <selector|--networkidle|--load|--domcontentloaded> [timeout-ms]",
         "Wait for an element to become visible, or for the given load state. Default timeout 15000ms."),
        ("upload", "upload <selector> <file1> [file2...]",
         "Set one or more files on a file input."),
        ("viewport", "viewport <WxH>",
         "Set the viewport size (e.g. 1920x1080, 375x812)."),
    ]),
    ("Dialogs", [
        ("dialog-accept", "dialog-accept [text]",
         "Auto-accept future dialogs, optionally answering prompts with `text`."),
        ("dialog-dismiss", "dialog-dismiss",
         "Auto-dismiss future dialogs."),
        ("dialog", "dialog [--clear]",
         "Show captured dialog events (`--clear` empties the buffer)."),
    ]),
    ("Inspection & Debugging", [
        ("js", "js <expression>",
         "Evaluate a JavaScript expression on the page and print the result."),
        ("eval", "eval <js-file>",
         "Evaluate JavaScript from a file (path must be under /tmp or the working directory)."),
        ("css", "css <selector> <property>",
         "Print the computed CSS property value of an element."),
        ("attrs", "attrs <selector>",
         "Print an element's attributes as JSON."),
        ("console", "console [--clear|--errors]",
         "Show buffered console messages (`--errors`: errors and warnings only)."),
        ("network", "network [--clear]",
         "Show buffered network requests: method, URL, status, duration, size."),
        ("is", "is <property> <selector>",
         "Check element state. Properties: visible, hidden, enabled, disabled, checked, editable, focused."),
        ("perf", "perf",
         "Navigation timing breakdown (DNS, TCP, TTFB, download, DOM ready, load)."),
    ]),
    ("Cookies, Session & Identity", [
        ("cookie", "cookie <name>=<value>",
         "Set a cookie on the current page's domain."),
        ("cookie-import", "cookie-import <json-file>",
         "Import cookies from a JSON array file (path must be under /tmp or the working directory)."),
        ("cookie-import-browser", "cookie-import-browser [browser] [--domain <domain>]",
         "Import cookies from an installed Chromium browser (Comet, Chrome, Arc, Brave, Edge). "
         "With `--domain` imports directly; otherwise opens the picker UI."),
        ("cookies", "cookies",
         "Dump the browser context's cookies as JSON."),
        ("storage", "storage [set <key> <value>]",
         "Show localStorage and sessionStorage, or set a localStorage key."),
        ("header", "header <name>:<value>",
         "Set an extra HTTP header for subsequent requests."),
        ("useragent", "useragent <string>",
         "Set the user agent (recreates the browser context)."),
    ]),
    ("Visual Capture", [
        ("screenshot", "screenshot [path]",
         "Full-page screenshot (default /tmp/browse-screenshot.png). "
         "Paths must be under /tmp or the working directory."),
        ("pdf", "pdf [path]",
         "Save the page as an A4 PDF (default /tmp/browse-page.pdf)."),
        ("responsive", "responsive [prefix]",
         "Capture mobile (375x812), tablet (768x1024), and desktop (1280x720) screenshots."),
    ]),
    ("Tabs", [
        ("tabs", "tabs",
         "List open tabs with id, title, and URL (active tab marked)."),
        ("tab", "tab <id>",
         "Switch to a tab by id."),
        ("newtab", "newtab [url]",
         "Open a new tab, optionally navigating to a URL."),
        ("closetab", "closetab [id]",
         "Close the current tab, or a specific tab by id."),
    ]),
    ("Multi-Step", [
        ("chain", "chain",
         "Run a JSON array of commands in sequence, read from stdin: "
         "`echo '[[\"goto\",\"url\"],[\"text\"]]' | browse chain`."),
    ]),
    ("Server", [
        ("status", "status",
         "Server health, current URL, tab count, and PID."),
        ("stop", "stop",
         "Stop the background server."),
        ("restart", "restart",
         "Restart the background server (fresh browser; tabs and refs are cleared)."),
    ]),
]


def parse_registry(source: str) -> set:
    """Extract the union of command names from the three registry Sets."""
    commands = set()
    for set_name in REGISTRY_SETS:
        match = re.search(
            r"export const " + set_name + r"\s*=\s*new Set\(\[(.*?)\]\)",
            source,
            re.DOTALL,
        )
        if not match:
            sys.exit("ERROR: could not find %s in %s" % (set_name, COMMANDS_TS))
        body = match.group(1)
        # Strip // line comments and /* */ block comments inside the array.
        body = re.sub(r"/\*.*?\*/", "", body, flags=re.DOTALL)
        body = re.sub(r"//[^\n]*", "", body)
        names = re.findall(r"'([^']+)'|\"([^\"]+)\"", body)
        names = [a or b for a, b in names]
        if not names:
            sys.exit("ERROR: %s parsed as empty in %s" % (set_name, COMMANDS_TS))
        dupes = commands.intersection(names)
        if dupes:
            sys.exit("ERROR: command(s) in multiple registry sets: %s" % ", ".join(sorted(dupes)))
        commands.update(names)
    return commands


def validate(registry: set) -> None:
    documented = set()
    errors = []
    for _, entries in GROUPS:
        for name, _, _ in entries:
            if name in documented:
                errors.append("Command documented twice: %s" % name)
            documented.add(name)
            if name not in registry:
                errors.append("Documented command not in browse/src/commands.ts: %s" % name)
    for name in sorted(registry - documented):
        errors.append(
            "Registry command missing documentation (add it to scripts/gen_browse_reference.py): %s" % name
        )
    if errors:
        for e in errors:
            print("ERROR: %s" % e, file=sys.stderr)
        sys.exit(1)


def escape_cell(text: str) -> str:
    """GFM table cells require literal pipes escaped, including inside code spans."""
    return text.replace("|", "\\|")


def render(registry: set) -> str:
    lines = [BEGIN_MARKER, ""]
    lines.append(
        "_Generated from `browse/src/commands.ts` (%d commands). Do not edit by hand — "
        "regenerate with `python3 scripts/gen_browse_reference.py`._" % len(registry)
    )
    for title, entries in GROUPS:
        lines.append("")
        lines.append("### %s" % title)
        lines.append("")
        lines.append("| Command | Description |")
        lines.append("| --- | --- |")
        for _, usage, description in entries:
            lines.append("| `%s` | %s |" % (escape_cell(usage), escape_cell(description)))
    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def main() -> None:
    registry = parse_registry(COMMANDS_TS.read_text(encoding="utf-8"))
    validate(registry)

    skill = SKILL_PATH.read_text(encoding="utf-8")
    begin = skill.find(BEGIN_MARKER)
    end = skill.find(END_MARKER)
    if begin == -1 or end == -1 or end < begin:
        sys.exit(
            "ERROR: markers not found in %s\nExpected %s ... %s" % (SKILL_PATH, BEGIN_MARKER, END_MARKER)
        )
    if skill.find(BEGIN_MARKER, begin + 1) != -1 or skill.find(END_MARKER, end + 1) != -1:
        sys.exit("ERROR: duplicate markers in %s" % SKILL_PATH)

    updated = skill[:begin] + render(registry) + skill[end + len(END_MARKER):]

    if "--check" in sys.argv[1:]:
        if updated != skill:
            sys.exit(
                "ERROR: skills/browse/SKILL.md command reference is stale.\n"
                "Run: python3 scripts/gen_browse_reference.py"
            )
        print("Command reference is up to date (%d commands)." % len(registry))
        return

    if updated == skill:
        print("No changes — command reference already current (%d commands)." % len(registry))
        return
    SKILL_PATH.write_text(updated, encoding="utf-8")
    print("Updated %s (%d commands)." % (SKILL_PATH, len(registry)))


if __name__ == "__main__":
    main()
