#!/usr/bin/env bun
// Generates runtime/src/generated/ui-embed.ts: one `with { type: 'file' }`
// import per file in runtime/ui/dist, so `bun build --compile` embeds the
// built page in the counsel-os binary (packaging spec §3.2). Git-ignored;
// written by `bun run build:runtime`. Never imported from the checkout.
import { mkdirSync, readdirSync, statSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

const root = resolve(import.meta.dir, '..');
const dist = resolve(root, 'runtime', 'ui', 'dist');
const outDir = resolve(root, 'runtime', 'src', 'generated');

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir).sort()) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

export function renderUiEmbedModule(files: string[]): string {
  // `.map` files are a debugging aid the binary need not carry.
  const kept = files.filter(f => !f.endsWith('.map'));
  const imports = kept.map((f, i) => `import u${i} from '../../../runtime/ui/dist/${f}' with { type: 'file' };`).join('\n');
  const entries = kept.map((f, i) => `  ${JSON.stringify(f)}: u${i},`).join('\n');
  return `// GENERATED by scripts/gen_ui_embed.ts (bun run build:runtime). Do not edit; git-ignored.
import type { EmbeddedUi } from '../core/embedded';

${imports}

export const ui: EmbeddedUi = {
  files: {
${entries}
  },
};
`;
}

if (import.meta.main) {
  let files: string[];
  try {
    files = walk(dist).map(f => relative(dist, f).split('\\').join('/'));
  } catch {
    console.error(`no built UI at ${dist} — run \`bun run ui:build\` first`);
    process.exit(1);
  }
  if (!files.includes('index.html')) {
    console.error(`${dist} has no index.html — not a built UI`);
    process.exit(1);
  }
  mkdirSync(outDir, { recursive: true });
  await Bun.write(join(outDir, 'ui-embed.ts'), renderUiEmbedModule(files));
  console.log(`ui embed: ${files.filter(f => !f.endsWith('.map')).length} files`);
}
